import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { isMainModule } from '../../utils/main-module.ts';
import { readJson } from '../../utils/read-file.ts';
import { repoRoot as root } from '../../lib/arena/repo-root.ts';
import { fieldEntries } from '../../lib/arena/contract-shapes.ts';
import type { MemberCandidate, TypeContract } from '../../lib/arena/contract-shapes.ts';

export const API_TARGETS = [
  'frameworks/react/Api.generated.ts',
  'frameworks/angular/Api.generated.ts',
];

export const TYPES_DIR = 'contracts/api/types';

export const LOCALE_TYPE = 'ArenaLocale';

export const LOCALE_TARGETS = [
  'frameworks/react/LocaleDefaults.generated.ts',
  'frameworks/angular/LocaleDefaults.generated.ts',
];

export const node = {
  name: 'generate:api-types',
  reads: [TYPES_DIR],
  writes: [...API_TARGETS, ...LOCALE_TARGETS],
  feeds: [
    'build:angular-demo',
    'build:angular-package',
    'build:angular-tests',
    'build:demos',
    'build:react-package',
    'check:angular',
    'check:api',
    'check:arbitrary',
    'check:demos',
    'check:dimensions',
    'check:duplicate-constants',
    'check:generated',
    'check:icons',
    'check:layer-independence',
    'check:react-types',
    'check:script-tokens',
    'check:shared-arithmetic',
    'check:skills',
  ],
};

const HEADER =
  '/* GENERATED by scripts/generate/arena/generate-api-types.ts — edit contracts/api/types/, not this file.\n'
  + ' *\n'
  + ' * Every declaration here is a predefined object or an enum some Arena API\n'
  + ' * contract names. The same body is emitted into both layers so a component\'s\n'
  + ' * import never crosses the contracts/api/ <-> frameworks/ boundary — the rule\n'
  + ' * tokens.generated.* already carries. scripts/check/arena/check-api.ts asserts the\n'
  + ' * emitted files match contracts/api/types/. See contracts/api/AGENTS.md for the vocabulary. */';

const PRIMITIVE_TS: Record<string, string> = { string: 'string', number: 'number', boolean: 'boolean' };

export function loadTypes(dir = join(root, 'contracts/api/types')) {
  return readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .sort()
    .map((f) => readJson(join(dir, f)));
}

export function docComment(text: string, indent = '') {
  const lines = text.split('\n');
  if (lines.length === 1) return `${indent}/** ${text} */`;
  return [`${indent}/**`, ...lines.map((l) => `${indent} *  ${l}`), `${indent} */`].join('\n');
}

export function fieldType(field: MemberCandidate) {
  if (field.form === 'primitive') {
    const ts = field.type === undefined ? undefined : PRIMITIVE_TS[field.type];
    if (!ts) throw new Error(`fieldType: "${field.type}" is not one of string, number, boolean`);
    return ts;
  }
  if (field.form === 'enum') return field.type;
  if (field.form === 'array') {
    const ts = field.of === undefined ? undefined : PRIMITIVE_TS[field.of];
    if (!ts) throw new Error(`fieldType: a field of a predefined object may be an array of primitives, and "${field.of}" is not a primitive — R1`);
    return `readonly ${ts}[]`;
  }
  throw new Error(`fieldType: form "${field.form}" is not allowed inside a predefined object — R1, an object is pure data`);
}

export function enumLiteral(value: string | number) {
  return typeof value === 'number' ? String(value) : `'${value}'`;
}

export function renderApiModule(types: TypeContract[]) {
  const out = [HEADER];
  for (const type of types) {
    out.push('');
    if (type.description) out.push(docComment(type.description));
    if (type.kind === 'enum') {
      out.push(`export type ${type.name} = ${(type.values ?? []).map(enumLiteral).join(' | ')};`);
      continue;
    }
    if (type.kind !== 'object') {
      throw new Error(`renderApiModule: unknown kind "${type.kind}" on type "${type.name}"`);
    }
    out.push(`export interface ${type.name} {`);
    for (const [name, field] of fieldEntries(type.fields)) {
      if (field.description) out.push(docComment(field.description, '  '));
      out.push(`  ${name}${field.required ? '' : '?'}: ${fieldType(field)};`);
    }
    out.push('}');
  }
  return `${out.join('\n')}\n`;
}

const LOCALE_HEADER =
  '/* GENERATED by scripts/generate/arena/generate-api-types.ts from the field defaults of\n'
  + ' * contracts/api/types/arena-locale.json. Edit that file, not this one. */';

export function renderLocaleDefaults(types: TypeContract[]) {
  const type = types.find((one) => one.name === LOCALE_TYPE);
  if (!type || type.kind !== 'object') {
    throw new Error(`renderLocaleDefaults: contracts/api/types/ declares no object named ${LOCALE_TYPE}`);
  }
  const lines = [];
  for (const [name, field] of fieldEntries(type.fields)) {
    if (field.form !== 'primitive' || field.type !== 'string' || typeof field.default !== 'string') {
      throw new Error(`renderLocaleDefaults: ${LOCALE_TYPE}.${name} carries no string default, and the `
        + 'default is the word Arena draws when nothing is provided');
    }
    lines.push(`  ${name}: ${JSON.stringify(field.default)},`);
  }
  return `${LOCALE_HEADER}\n\nimport type { ArenaLocale } from './Api.generated';\n\n`
    + `export const ARENA_DEFAULT_LOCALE: ArenaLocale = Object.freeze({\n${lines.join('\n')}\n});\n`;
}

export function buildApiModules() {
  const types = loadTypes();
  const body = renderApiModule(types);
  const defaults = renderLocaleDefaults(types);
  return new Map<string, string>([
    ...API_TARGETS.map((path) => [path, body] as [string, string]),
    ...LOCALE_TARGETS.map((path) => [path, defaults] as [string, string]),
  ]);
}

function main() {
  for (const [path, source] of buildApiModules()) {
    writeFileSync(join(root, path), source);
    console.log(`build-api-types: wrote ${path}`);
  }
}

if (isMainModule(import.meta.url)) main();
