/* The half of an npm page that is the same page in both packages. Two documents with one file
 * name are one document rendered per layer, so what they share is a single source said twice: it
 * was said twice by hand, 8,700 characters of it, and the two had already drifted in wording
 * elsewhere on the page. Each region is emitted between markers a person placed, because where a
 * section sits on the page is the author's decision and only what it says is this file's. The
 * voice section is the one that is not verbatim: its catalogue and the count in its opening
 * sentence come from contracts/design/extension.*.json, which is what made "two ship today" a
 * sentence that goes false the day a third one lands. Everything a layer decides, the import
 * idiom, what the package exports and how a layout is composed, stays hand-written in each. */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { isMainModule } from '../../utils/main-module.ts';
import { repoRoot as root } from '../../lib/arena/repo-root.ts';
import { voiceTable, voices, countWord } from './generate-voices.ts';

export const TARGETS = [
  'frameworks/react/PACKAGE.md',
  'frameworks/angular/PACKAGE.md',
];

export const node = {
  name: 'generate:npm-pages',
  reads: ['contracts/design/extension.*.json'],
  writes: TARGETS,
  feeds: [
    'build:angular-package',
    'build:react-package',
    'check:arbitrary',
    'check:dimensions',
    'check:duplicate-constants',
    'check:generated',
    'check:icons',
    'check:layer-independence',
    'check:routes',
    'check:script-tokens',
    'check:skills',
  ],
};

export const openLine = (key: string) => `<!-- @shared ${key} GENERATED by bun run generate:npm-pages.`
  + ' Edit that script, not this copy. -->';
export const closeLine = (key: string) => `<!-- @shared ${key} end -->`;
export const opensAt = (key: string) => new RegExp(`^<!-- @shared ${key} GENERATED `);

export function shipped(base = root) {
  const catalogue = voices(base);
  const extensions = catalogue.length - 1;
  const word = countWord(extensions);
  return { catalogue, extensions, capitalized: `${word[0]?.toUpperCase() ?? ''}${word.slice(1)}` };
}

export const REGIONS: Record<string, (base?: string) => string> = {
  repository: () => `## It works with the repository, and that is the point

Source, guidelines and full documentation: **https://github.com/dravensoft-dev/arena**

That repository is not just where the code comes from. It ships as a **Claude Code plugin**
and as an **Agent Skill**, and installing either hands an agent the whole design language:
the normative colour, spacing and voice guidelines, the API contract of every component, the
accessibility pattern each one binds, and a usage document per component with its Do and its
Don't. An agent that has read those does not guess at Arena; it builds with it. So the fastest
way to adopt this package is to install the plugin, or point your agent at the repository's
\`SKILL.md\`, and then ask for the screen you want.

The package is the code. The repository is the criterion.`,

  skin: () => `## Declare your skin

Write \`arena.config.json\` in your project root. This is the whole file, with one palette and
three fonts served by Google Fonts, and it is enough to start:

\`\`\`json
{
  "palettes": [
    {
      "name": "dark",
      "default": true,
      "polarity": "dark",
      "colors": {
        "base-100": "#141010",
        "base-200": "#1d1715",
        "base-300": "#241c19",
        "base-content": "#f3ede5",
        "primary": "#b52a20",
        "primary-content": "#ffffff",
        "secondary": "#c5a059",
        "secondary-content": "#141010",
        "neutral": "#2c221e",
        "neutral-content": "#d8cfc4",
        "info": "#3182ce",
        "info-content": "#141010",
        "success": "#38a169",
        "success-content": "#141010",
        "warning": "#ecc94b",
        "warning-content": "#141010",
        "error": "#e85151",
        "error-content": "#ffffff",
        "cat-1": "#3c7b0a",
        "cat-2": "#3b63be",
        "cat-3": "#0a924b",
        "cat-4": "#6a59bc",
        "cat-5": "#00a3c0",
        "cat-6": "#884da9",
        "cat-7": "#00a99a",
        "cat-8": "#984697"
      }
    }
  ],
  "fonts": {
    "display": { "family": "Archivo", "src": "https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;700;800;900&display=swap" },
    "body": { "family": "Familjen Grotesk", "src": "https://fonts.googleapis.com/css2?family=Familjen+Grotesk:wght@400;500;600;700;800;900&display=swap" },
    "mono": { "family": "Spline Sans Mono", "src": "https://fonts.googleapis.com/css2?family=Spline+Sans+Mono:wght@400;500;600;700;800;900&display=swap" }
  }
}
\`\`\`

\`arena.config.example.json\` in this package is the same file with both Dravensoft palettes in
it, ready to copy and edit.

What each part means:

- **\`palettes\`** is an array, so declare as many as you want. Exactly one is the \`default\` and
  reaches \`:root\`; every other one becomes a class, \`.arena-<name>\`, that you put on
  \`<html>\` to switch skin.
- **\`polarity\`** is \`dark\` or \`light\`. It decides the native date picker's colour and it is
  what a first visit matches \`prefers-color-scheme\` against.
- **\`colors\`** takes all 27 keys above. \`error-fill\` is the only optional one: leave it out and
  Arena darkens \`error\` in oklab for the single filled danger surface it has.
- **\`cat-1\`** through **\`cat-8\`** are the chart ramp. Their order is their identity, so slot 3
  is always slot 3, and they are never used to mean anything, only to tell series apart.
- **\`fonts\`** fills the three families Arena reads. \`src\` takes either a stylesheet URL, as
  above, or a font binary you host yourself, which becomes an \`@font-face\`:
  \`{ "family": "Archivo", "src": "/fonts/archivo.woff2", "weight": "400 900" }\`.
- **\`stylesheet\`** is optional and names what you render, so you send nothing else. See
  Build to production, below.`,

  tail: () => `## Why might this package's latest version not match Arena's latest version?

[Why are the published package versions not identical?](https://github.com/dravensoft-dev/arena/blob/main/.github/workflows/AGENTS.md#why-are-the-published-package-versions-not-identical)

## License

MIT. See the repository.`,

  voices: (base = root) => {
    const { capitalized } = shipped(base);
    return [
      `## Pick a design extension

Arena ships one visual voice by default: hairline grouping, flat hierarchy, no resting depth, made
for reading a lot of data at once. A **design extension** is a second voice for the work that is
not that. ${capitalized} ship today, and each is named for the job rather than for how it looks:

`.trimEnd(),
      '',
      ...voiceTable(base),
      '',
      `

No two of them group by the same mechanism, and that is enforced rather than intended: Arena's
build fails if two voices claim one. So they differ in kind and not by degree, which is what makes
picking one a decision rather than a preference.

**Coming from 8.x: \`showcase\` is the voice that was called \`expressive\`.** It is the same voice
with the same values; only the name moved, because a voice should say the job it does the way
\`compact\` and \`comfortable\` do, and the old name said neither the job nor the mechanism. If your
\`arena.config.json\` selects \`"expressive"\`, write \`"showcase"\` instead, and if you put the old
class on an element by hand, write \`arena-showcase\` there. Nothing else changes.

There is no alias, on purpose: a name kept alive after it stopped being the name is a second thing
to learn. What you get instead is a build that stops and tells you what this package does ship,
which is the whole of the migration.

\`\`\`html
<html class="arena-showcase">
\`\`\`

\`showcase\` softens every corner, drops the border around a surface and lets elevation and air do
the grouping instead, gives a surface more room inside it and more ground around it, lifts a
control under the pointer, and answers it like an object with mass rather than instantly. Put the
class on the root, or on any container to scope it to part of a page.

\`editorial\` goes the other way and draws nothing: no border, no resting depth, and a card that
takes the page's own fill so it stops being a card. What carries the structure is the distance
between things, which it opens to eight times the gap inside a group, over headings set heavier
and prose set looser. Reach for it when the screen is something somebody reads rather than
operates.

Its depth is paid for differently in each polarity, and that is deliberate rather than an
inconsistency. A drop shadow is a darkening, so it separates a light card from a light page and
does almost nothing between a dark card and a dark page; in dark the voice uses a lit top edge
instead, which reads because it is light on dark. You get the right one for the palette you are
in, and if you select the extension in \`arena.config.json\` you get it per palette without writing
a class.

It composes with everything else, because the three things change different values: a palette
class carries colour, a density class carries how large the controls are, and an extension carries
the shape and the depth. \`<html class="arena-light arena-comfortable arena-showcase">\` is a
light, roomy, showcase page and needs no ordering care.

Two things it deliberately does not do. It does not change control heights or row padding: that is
the density's job, and \`arena-comfortable\` takes a control to a 48px touch target while
\`arena-compact\` tightens it for dense work. Pick one of those two, never both. And an extension
does not touch the border of a button or an input, because that boundary is what carries the 3:1
those controls owe whatever voice they are speaking in.

Write no extension of your own: an extension is measured against Arena's accessibility floors
before it ships, and a hand-written scope class is a claim nobody checked.

### Selecting it in \`arena.config.json\`

\`\`\`json
{ "extension": "showcase" }
\`\`\`

The field is **optional and never a list**, so a build carries at most one extension and no
cascade decides between two. Omit it and you get Arena's default appearance. Write \`"none"\` and
you get the same thing, said out loud, which is what a project turns an extension off with rather
than deleting the line.

Nothing else is a word. \`"default"\` is not a way to ask for the default appearance: it is an
unknown extension name and fails the build, and it stays that way unless an extension is one day
actually called \`default\`. A config that quietly resolved a name Arena does not ship would be a
build painting something nobody chose.

The value reaches \`:root\` in the generated theme, so with the field set you need no class of your
own. Putting \`arena-showcase\` on an element is still how you scope one to part of a page.

A palette may not be named after an extension the package ships, since both would be the class
\`.arena-<name>\`. The CLI fails that rather than letting the two silently contend.`.trimStart(),
    ].join('\n');
  },
};

export function renderRegion(key: string, base = root) {
  const render = REGIONS[key];
  if (!render) throw new Error(`generate-npm-pages: no region called ${key}`);
  return [openLine(key), '', render(base), '', closeLine(key)].join('\n');
}

export function applyRegion(source: string, key: string, region: string) {
  const lines = source.split('\n');
  const from = lines.findIndex((line) => opensAt(key).test(line));
  if (from === -1)
    throw new Error(
      `generate-npm-pages: no @shared ${key} region to write into. A person places the markers, `
      + 'because where a section sits on a page a consumer reads is the page\'s decision and only '
      + 'what the section says belongs to this script.',
    );
  const to = lines.indexOf(closeLine(key), from);
  if (to === -1) throw new Error(`generate-npm-pages: the @shared ${key} region opens and never closes`);
  return [...lines.slice(0, from), ...region.split('\n'), ...lines.slice(to + 1)].join('\n');
}

export function renderTarget(source: string, base = root) {
  return Object.keys(REGIONS).reduce(
    (text, key) => applyRegion(text, key, renderRegion(key, base)), source,
  );
}

export function writePages({ base = root, read = readFileSync, write = writeFileSync } = {}) {
  const written = [];
  for (const target of TARGETS) {
    const path = join(base, target);
    const before = read(path, 'utf8');
    const after = renderTarget(before, base);
    if (after === before) continue;
    write(path, after);
    written.push(target);
  }
  return written;
}

function main() {
  const written = writePages();
  for (const target of written) console.log(`generate-npm-pages: wrote ${target}`);
  console.log(`generate-npm-pages: ${TARGETS.length} page(s) carry ${Object.keys(REGIONS).length} shared region(s) each`);
}

if (isMainModule(import.meta.url)) main();
