import test from 'node:test';
import assert from 'node:assert/strict';
import { renderApiModule, docComment, fieldType, API_TARGETS, buildApiModules, LOCALE_TARGETS, renderLocaleDefaults } from './generate-api-types.ts';

test('an enum renders as a string-literal union', () => {
  const out = renderApiModule([{ name: 'ArenaDirection', kind: 'enum', values: ['up', 'down'] }]);
  assert.match(out, /export type ArenaDirection = 'up' \| 'down';/);
});

test('renderApiModule emits a numeric enum unquoted', () => {
  const out = renderApiModule([{ name: 'ArenaCatSlot', kind: 'enum', description: 'x', values: [1, 2, 3] }]);
  assert.match(out, /export type ArenaCatSlot = 1 \| 2 \| 3;/);
});

test('renderApiModule still quotes a string enum', () => {
  const out = renderApiModule([{ name: 'Dir', kind: 'enum', description: 'x', values: ['up', 'down'] }]);
  assert.match(out, /export type Dir = 'up' \| 'down';/);
});

test('an object renders as an interface, with optional fields marked optional', () => {
  const out = renderApiModule([{
    name: 'ArenaCrumb', kind: 'object',
    fields: {
      label: { form: 'primitive', type: 'string', required: true },
      href: { form: 'primitive', type: 'string' },
    },
  }]);
  assert.match(out, /export interface ArenaCrumb \{/);
  assert.match(out, /^ {2}label: string;$/m);
  assert.match(out, /^ {2}href\?: string;$/m);
});

test('an enum-typed field renders as the enum name, not as a re-inlined union', () => {
  const out = renderApiModule([{
    name: 'ArenaStatDelta', kind: 'object',
    fields: { direction: { form: 'enum', type: 'ArenaDirection', required: true } },
  }]);
  assert.match(out, /^ {2}direction: ArenaDirection;$/m);
});

test('a description becomes a doc comment on the type and on the field', () => {
  const out = renderApiModule([{
    name: 'ArenaCrumb', kind: 'object', description: 'One entry in a trail.',
    fields: { label: { form: 'primitive', type: 'string', required: true, description: 'What the crumb reads.' } },
  }]);
  assert.match(out, /\/\*\* One entry in a trail\. \*\/\nexport interface ArenaCrumb \{/);
  assert.match(out, /^ {2}\/\*\* What the crumb reads\. \*\/$/m);
});

test('a multi-line description becomes a block comment, so no prose is lost', () => {
  const out = docComment('first line\nsecond line');
  assert.equal(out, '/**\n *  first line\n *  second line\n */');
});

test('the header names the generator and forbids editing the output', () => {
  const out = renderApiModule([]);
  assert.match(out, /GENERATED by scripts\/generate\/arena\/generate-api-types\.ts/);
  assert.match(out, /edit contracts\/api\/types\/, not this file/);
});

test('a field that is a slot or an event is refused -- R1, a predefined object is pure data', () => {
  assert.throws(() => fieldType({ form: 'slot' }), /R1/);
  assert.throws(() => fieldType({ form: 'event' }), /R1/);
  assert.throws(() => fieldType({ form: 'consumerData' }), /R1/);
});

test('a field may be an array of primitives, and may not be an array of objects', () => {

  assert.equal(fieldType({ form: 'array', of: 'number' }), 'readonly number[]');
  assert.equal(fieldType({ form: 'array', of: 'string' }), 'readonly string[]');
  assert.throws(() => fieldType({ form: 'array', of: 'ArenaSeries' }), /R1/);
  assert.throws(() => fieldType({ form: 'array' }), /R1/);
});

test('an unknown kind is refused rather than silently skipped', () => {
  assert.throws(() => renderApiModule([{ name: 'X', kind: 'mapped' }]), /unknown kind "mapped"/);
});

test('both layers receive the identical body -- one contract, two import paths', () => {
  const modules = buildApiModules();
  assert.deepEqual([...modules.keys()], [...API_TARGETS, ...LOCALE_TARGETS]);
  const [a, b, c, d] = [...modules.values()];
  assert.equal(a, b);
  assert.equal(c, d);
});

test('API_TARGETS names one file per layer, and neither lives under contracts/api/', () => {
  assert.deepEqual(API_TARGETS, [
    'frameworks/react/Api.generated.ts',
    'frameworks/angular/Api.generated.ts',
  ]);
});

test('renderLocaleDefaults writes every ArenaLocale field default, in declaration order', () => {
  const body = renderLocaleDefaults([{
    name: 'ArenaLocale', kind: 'object', fields: {
      locale: { form: 'primitive', type: 'string', required: true, default: 'en-GB' },
      tagRemove: { form: 'primitive', type: 'string', required: true, default: 'Remove' },
    },
  }]);
  assert.match(body, /import type \{ ArenaLocale \} from '\.\/Api\.generated';/);
  assert.match(body, /export const ARENA_DEFAULT_LOCALE: ArenaLocale = Object\.freeze\(\{\n {2}locale: "en-GB",\n {2}tagRemove: "Remove",\n\}\);/);
});

test('renderLocaleDefaults refuses a field with no string default and names it', () => {
  assert.throws(() => renderLocaleDefaults([{
    name: 'ArenaLocale', kind: 'object',
    fields: { tagRemove: { form: 'primitive', type: 'string', required: true } },
  }]), /ArenaLocale\.tagRemove/);
});

test('renderLocaleDefaults refuses a tree that declares no ArenaLocale', () => {
  assert.throws(() => renderLocaleDefaults([]), /ArenaLocale/);
});

test('buildApiModules emits the locale defaults into both layers', () => {
  assert.deepEqual(LOCALE_TARGETS, [
    'frameworks/react/LocaleDefaults.generated.ts',
    'frameworks/angular/LocaleDefaults.generated.ts',
  ]);
  const modules = buildApiModules();
  for (const path of LOCALE_TARGETS) assert.match(modules.get(path) ?? '', /ARENA_DEFAULT_LOCALE/, path);
});
