/* The half of an npm page that is the same page in both packages. Two documents with one file
 * name are one document rendered per layer, so what they share is a single source said twice: it
 * was said twice by hand, 8,700 characters of it, and the two had already drifted in wording
 * elsewhere on the page. Each region is emitted between markers a person placed, because where a
 * section sits on the page is the author's decision and only what it says is this file's.
 * Everything a layer decides, the import idiom, what the package exports and how a layout is
 * composed, stays hand-written in each. */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { isMainModule } from '../../utils/main-module.ts';
import { repoRoot as root } from '../../lib/arena/repo-root.ts';

export const TARGETS = [
  'frameworks/react/PACKAGE.md',
  'frameworks/angular/PACKAGE.md',
];

export const node = {
  name: 'generate:npm-pages',
  reads: [...TARGETS],
  writes: TARGETS,
  feeds: [
    'build:angular-package',
    'build:react-package',
    'check:arbitrary',
    'check:dimensions',
    'check:duplicate-constants',
    'check:generated',
    'check:icons',
    'check:layer-independence',
    'check:routes',
    'check:script-tokens',
    'check:skills', 'build:site'],
};

export const openLine = (key: string) => `<!-- @shared ${key} GENERATED by bun run generate:npm-pages.`
  + ' Edit that script, not this copy. -->';
export const closeLine = (key: string) => `<!-- @shared ${key} end -->`;
export const opensAt = (key: string) => new RegExp(`^<!-- @shared ${key} GENERATED `);

export const REGIONS: Record<string, (base?: string) => string> = {
  repository: () => `## It works with the repository, and that is the point

See it before you install it: **https://arena.dravensoft.org** has the guidelines, a kitchen sink
and a playground for every component. Source and full documentation:
**https://github.com/dravensoft-dev/arena**

That repository is not just where the code comes from. It ships as a **Claude Code plugin**
and as an **Agent Skill**, and installing either hands an agent the whole design language:
the normative colour and spacing guidelines, the API contract of every component, the
accessibility pattern each one binds, and a usage document per component with its Do and its
Don't. An agent that has read those does not guess at Arena; it builds with it. So the fastest
way to adopt this package is to install the plugin, or point your agent at the repository's
\`SKILL.md\`, and then ask for the screen you want.

The package is the code. The repository is the criterion.`,

  skin: () => `## Declare your skin

Write \`arena.config.json\` in your project root. This is the whole file, with one palette and
three fonts served by Google Fonts, and it is enough to start:

\`\`\`json
{
  "palettes": [
    {
      "name": "dark",
      "default": true,
      "polarity": "dark",
      "colors": {
        "base-100": "#141010",
        "base-200": "#1d1715",
        "base-300": "#241c19",
        "base-content": "#f3ede5",
        "primary": "#b52a20",
        "primary-content": "#ffffff",
        "secondary": "#c5a059",
        "secondary-content": "#141010",
        "neutral": "#2c221e",
        "neutral-content": "#d8cfc4",
        "info": "#3182ce",
        "info-content": "#141010",
        "success": "#38a169",
        "success-content": "#141010",
        "warning": "#ecc94b",
        "warning-content": "#141010",
        "error": "#e85151",
        "error-content": "#ffffff",
        "error-fill": "#ce3838",
        "cat-1": "#3c7b0a",
        "cat-2": "#3b63be",
        "cat-3": "#0a924b",
        "cat-4": "#6a59bc",
        "cat-5": "#00a3c0",
        "cat-6": "#884da9",
        "cat-7": "#00a99a",
        "cat-8": "#984697"
      }
    }
  ],
  "fonts": {
    "display": { "family": "Archivo", "src": "https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;700;800;900&display=swap" },
    "body": { "family": "Familjen Grotesk", "src": "https://fonts.googleapis.com/css2?family=Familjen+Grotesk:wght@400;500;600;700;800;900&display=swap" },
    "mono": { "family": "Spline Sans Mono", "src": "https://fonts.googleapis.com/css2?family=Spline+Sans+Mono:wght@400;500;600;700;800;900&display=swap" }
  }
}
\`\`\`

\`arena.config.example.json\` in this package is the same file with both Dravensoft palettes in
it, ready to copy and edit.

What each part means:

- **\`palettes\`** is an array, so declare as many as you want. Exactly one is the \`default\` and
  reaches \`:root\`; every other one becomes a class, \`.arena-<name>\`, that you put on
  \`<html>\` to switch skin.
- **\`polarity\`** is \`dark\` or \`light\`. It decides the native date picker's colour and it is
  what a first visit matches \`prefers-color-scheme\` against.
- **\`colors\`** takes all 27 keys above. \`error-fill\` is the only optional one: leave it out and
  Arena darkens \`error\` in oklab for the single filled danger surface it has.
- **\`cat-1\`** through **\`cat-8\`** are the chart ramp. Their order is their identity, so slot 3
  is always slot 3, and they are never used to mean anything, only to tell series apart.
- **\`fonts\`** fills the three families Arena reads. \`src\` takes either a stylesheet URL, as
  above, or a font binary you host yourself, which becomes an \`@font-face\`:
  \`{ "family": "Archivo", "src": "/fonts/archivo.woff2", "weight": "400 900" }\`.
- **\`stylesheet\`** is optional and names what you render, so you send nothing else. See
  Build to production, below.
- **\`stylePlugins\`** is optional and names the appearance. It is a list, because a build can
  carry more than one register, and the first entry is what a page with no class on it looks
  like; every later one emits under \`.arena-<name>\` and is a difference. An entry is the word
  \`default\`, which is the appearance this package installs with, or a path to a directory of
  your own holding \`plugin.tokens.json\` and optionally \`plugin.css\`. The first entry answers
  every role Arena declares, and the command refuses one that does not: a custom property with no
  value is invalid at computed-value time, so an unanswered role is a missing border rather than
  a plainer look. Declare a list without \`default\` and you do not receive its stylesheet, the
  same way the preflight can already be dropped.`,

  tail: () => `## Why might this package's latest version not match Arena's latest version?

[Why are the published package versions not identical?](https://github.com/dravensoft-dev/arena/blob/main/.github/workflows/AGENTS.md#why-are-the-published-package-versions-not-identical)

## License

MIT. See the repository.`,
};

export function renderRegion(key: string, base = root) {
  const render = REGIONS[key];
  if (!render) throw new Error(`generate-npm-pages: no region called ${key}`);
  return [openLine(key), '', render(base), '', closeLine(key)].join('\n');
}

export function applyRegion(source: string, key: string, region: string) {
  const lines = source.split('\n');
  const from = lines.findIndex((line) => opensAt(key).test(line));
  if (from === -1)
    throw new Error(
      `generate-npm-pages: no @shared ${key} region to write into. A person places the markers, `
      + 'because where a section sits on a page a consumer reads is the page\'s decision and only '
      + 'what the section says belongs to this script.',
    );
  const to = lines.indexOf(closeLine(key), from);
  if (to === -1) throw new Error(`generate-npm-pages: the @shared ${key} region opens and never closes`);
  return [...lines.slice(0, from), ...region.split('\n'), ...lines.slice(to + 1)].join('\n');
}

export function renderTarget(source: string, base = root) {
  return Object.keys(REGIONS).reduce(
    (text, key) => applyRegion(text, key, renderRegion(key, base)), source,
  );
}

export function writePages({ base = root, read = readFileSync, write = writeFileSync } = {}) {
  const written = [];
  for (const target of TARGETS) {
    const path = join(base, target);
    const before = read(path, 'utf8');
    const after = renderTarget(before, base);
    if (after === before) continue;
    write(path, after);
    written.push(target);
  }
  return written;
}

function main() {
  const written = writePages();
  for (const target of written) console.log(`generate-npm-pages: wrote ${target}`);
  console.log(`generate-npm-pages: ${TARGETS.length} page(s) carry ${Object.keys(REGIONS).length} shared region(s) each`);
}

if (isMainModule(import.meta.url)) main();
