/* The repertoire page, emitted from the one file that holds the repertoire. A range written into
 * prose beside the manifest that declares it is a range that disagrees with itself on the release
 * nobody thought about, so the peer table and the axis tables are regions rather than sentences,
 * and support-matrix.ts is the only place either is said. The markers are placed by a person,
 * because where a table sits on the page is the author's decision and only what it says is this
 * script's: the same split generate-npm-pages.ts makes for the half of an npm page both layers
 * share. */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { isMainModule } from '../../utils/main-module.ts';
import { repoRoot as root } from '../../lib/arena/repo-root.ts';
import { AXES, renderAxes, renderPeers } from '../../lib/arena/support-matrix.ts';

export const TARGET = 'skills/design/references/stack.md';

export const node = {
  name: 'generate:support',
  reads: [TARGET, 'scripts/lib/arena/support-matrix.ts'],
  writes: [TARGET],
  feeds: ['check:support', 'check:community', 'check:routes', 'build:site'],
};

export const openLine = (key: string) => `<!-- @support ${key} GENERATED by bun run generate:support.`
  + ' Edit that script, not this copy. -->';
export const closeLine = (key: string) => `<!-- @support ${key} end -->`;

export const REGIONS: Record<string, () => string> = {
  matrix: () => renderAxes(AXES),
  peers: () => renderPeers(),
};

export function emit(source: string) {
  let text = source;
  for (const [key, body] of Object.entries(REGIONS)) {
    const open = openLine(key);
    const close = closeLine(key);
    const from = text.indexOf(open);
    const to = text.indexOf(close);
    if (from === -1 || to === -1 || to < from) {
      throw new Error(`generate-support: ${TARGET} carries no @support ${key} region. The markers are `
        + 'placed by hand, so a region this script emits and the page does not open is a region '
        + 'nobody reads');
    }
    text = `${text.slice(0, from + open.length)}\n\n${body()}\n\n${text.slice(to)}`;
  }
  return text;
}

export function generateSupport(base = root) {
  const path = join(base, ...TARGET.split('/'));
  const emitted = emit(readFileSync(path, 'utf8'));
  writeFileSync(path, emitted);
  return emitted;
}

function main() {
  const emitted = generateSupport();
  console.log(`generate-support: ${TARGET}, ${Object.keys(REGIONS).length} region(s), `
    + `${emitted.length} character(s)`);
}

if (isMainModule(import.meta.url)) main();
