/* A design source is identified by its NAME, and the full path exists only to hand to Style
 * Dictionary, which reads one spelling and reports another back. It passes `source` straight to
 * glob, where a backslash escapes rather than separates, so the path goes in posix or it matches
 * no file at all on Windows; and it stamps each token's filePath with glob's posix answer, which
 * writes a Windows drive as //?/D:/ and therefore equals nothing any join produces. Comparing two
 * spellings of one file is the defect both halves of that caused, and a name has only one. */

import StyleDictionary from 'style-dictionary';
import { writeFileSync } from 'node:fs';
import nodePath, { join } from 'node:path';
import { toPosix } from '../../utils/posix-path.ts';
import type { PathModule } from '../../utils/posix-path.ts';
import { camel } from '../../utils/case.ts';
import { isMainModule } from '../../utils/main-module.ts';
import { serialize } from '../../lib/core/serialize-token.ts';
import { serializeScript } from '../../lib/core/serialize-script.ts';
import { repoRoot as root } from '../../lib/arena/repo-root.ts';
import { ARENA_EXT, childEntries, isStamped, isToken } from '../../lib/core/dtcg-shapes.ts';
import type { DtcgNode, DtcgToken, StampedToken } from '../../lib/core/dtcg-shapes.ts';

const HEADER = '/* GENERATED by Style Dictionary — edit contracts/design/, not this file. */';

export const FILES = [
  { out: 'palette.generated.css', blocks: [
    { selector: ':root', source: 'palette.dark.json' },
    { selector: '.arena-light', source: 'palette.light.json' },
  ] },
  { out: 'typography.generated.css', blocks: [
    { selector: ':root', source: 'typography.json' },
  ] },
  { out: 'spacing.generated.css', blocks: [
    { selector: ':root', source: 'spacing.json' },
    { selector: ':root', source: 'icon.json' },
    { selector: ':root', source: 'component.json' },
    { selector: '.arena-compact', source: 'density.compact.json' },
    { selector: '.arena-comfortable', source: 'density.comfortable.json' },
  ] },
  { out: 'effects.generated.css', blocks: [
    { selector: ':root', source: 'effects.json' },
    { selector: ':root', source: 'roles.json' },
    { selector: ':root', source: 'layering.json' },
    { selector: ':root', source: 'chart.json' },
    { selector: ':root', source: 'behaviour.json' },
    { selector: '.arena-expressive', source: 'extension.expressive.json' },
  ] },
];

export const RESOLVES_AGAINST = {
  'chart.json': ['spacing.json'],
  'roles.json': ['effects.json', 'palette.dark.json'],
  'extension.expressive.json': ['effects.json', 'typography.json', 'palette.dark.json'],
};

export const EXTENSION_PREFIX = 'extension.';

export const CATALOGUE = 'arena-extensions';

export const THEME_SCOPES = new Map<string, (selector: string) => string>([
  ['light', (s) => (s === ':root'
    ? '.arena-light'
    : `.arena-light${s}, .arena-light ${s}, ${s} .arena-light`)],
]);

export const themeOf = (token: { path?: string[] }) => {
  const first = token.path?.[0] ?? '';
  return THEME_SCOPES.has(first) ? first : '';
};

export const emittedName = (token: { name: string; path?: string[] }) =>
  (themeOf(token) ? (token.path ?? []).slice(1).join('-') : token.name);

const ALIAS = /^\{([^}]+)\}$/;

export function referenceOf(token: DtcgToken) {
  if (token.$type !== 'color') return null;
  const authored = token.original?.$value;
  if (typeof authored !== 'string') return null;
  const alias = ALIAS.exec(authored.trim());
  return alias ? `var(--${(alias[1] ?? '').replace(/\./g, '-')})` : null;
}

export function extensionsIn(blocks: { selector: string; source: string }[]) {
  return blocks
    .filter((b) => b.source.startsWith(EXTENSION_PREFIX))
    .map((b) => b.selector.replace(/^\.arena-/, ''))
    .sort();
}

export const SCRIPT_TARGETS = [
  'frameworks/react/Tokens.generated.js',
  'frameworks/angular/Tokens.generated.ts',
];

export const BREAKPOINT_TARGET = 'frameworks/tailwind/Breakpoints.generated.css';

export const SOURCES = [...new Set(FILES.flatMap((file) => file.blocks.map((b) => b.source)))];

export const CSS_TARGETS = FILES.map((file) => `contracts/design-generated/${file.out}`);

export const node = {
  name: 'generate:tokens',
  reads: [...new Set([...SOURCES, ...Object.values(RESOLVES_AGAINST).flat()])]
    .map((source) => `contracts/design/${source}`),
  writes: [...CSS_TARGETS, ...SCRIPT_TARGETS, BREAKPOINT_TARGET],
  feeds: [
    'build:angular-demo',
    'build:angular-package',
    'build:angular-tests',
    'build:react-package',
    'build:tailwind',
    'check:angular',
    'check:arbitrary',
    'check:cdk',
    'check:component-css',
    'check:contracts',
    'check:coverage',
    'check:dimensions',
    'check:duplicate-constants',
    'check:extensions',
    'check:generated',
    'check:icons',
    'check:layer-independence',
    'check:packages',
    'check:ramp',
    'check:script-tokens',
    'check:shared-arithmetic',
    'check:skills',
    'check:tailwind',
    'check:tailwind-generated',
    'check:boundary-contrast', 'check:text-contrast',
    'check:tokens',
  ],
};

const BREAKPOINT_HEADER =
  '/* GENERATED by scripts/generate/arena/generate-tokens.ts — edit contracts/design/spacing.json, not this file.\n'
  + ' *\n'
  + ' * Tailwind\'s breakpoint namespace, emitted as LITERALS and not as var() references,\n'
  + ' * because a media query condition holds no var(): Tailwind resolves a --breakpoint-*\n'
  + ' * value at build time to write the variant\'s @media. This is the one place an Arena\n'
  + ' * value is spelled twice, and it is generated so the two cannot drift. Tailwind\'s own\n'
  + ' * defaults are cleared first, the way every namespace in Theme.css clears its own:\n'
  + ' * Arena has three breakpoints, so a consumer gets three variants and no xl. */';

export async function buildBreakpointTheme() {
  const lines = [];
  for (const item of walk(await load('spacing.json'))) {
    if (!isTokenItem(item) || !/^bp-/.test(item.token.name)) continue;
    lines.push(`  --breakpoint-${item.token.name.slice(3)}:${serialize(item.token)};`);
  }
  return `${BREAKPOINT_HEADER}\n@theme {\n  --breakpoint-*: initial;\n${lines.join('\n')}\n}\n`;
}

const SCRIPT_HEADER =
  '/* GENERATED by scripts/generate/arena/generate-tokens.ts — edit contracts/design/, not this file.\n'
  + ' *\n'
  + ' * Every export here is a token flagged script-readable in contracts/design/ and\n'
  + ' * emitted as a bare number because JS arithmetic consumes it. Each one also\n'
  + ' * ships as a CSS custom property; scripts/check/arena/check-script-tokens.ts asserts the\n'
  + ' * two carry the same value. A value bound at import time cannot re-theme or\n'
  + ' * re-densify — that is the accepted price of reading it in JS at all. */';

const isScript = (token: DtcgToken) => token.$extensions?.[ARENA_EXT]?.script === true;

function scriptSources() {
  return [...new Set(FILES.flatMap((f) => f.blocks.map((b) => b.source)))];
}

export async function collectScriptTokens() {
  const out = [];
  for (const source of scriptSources()) {
    for (const item of walk(await load(source))) {
      if (!isTokenItem(item) || !isScript(item.token)) continue;
      out.push({
        cssName: item.token.name,
        jsName: camel(item.token.name),
        value: serializeScript(item.token),
        $description: item.token.$description,
        groups: item.groups,
      });
    }
  }
  return out;
}

async function catSlotCount() {
  let n = 0;
  for (const item of walk(await load('palette.dark.json'))) {
    if (isTokenItem(item) && /^color-cat-\d+$/.test(item.token.name)) n += 1;
  }
  return n;
}

export async function buildScriptModules() {
  const tokens = await collectScriptTokens();
  const lines = [SCRIPT_HEADER, ''];
  let emitted = null;
  for (const t of tokens) {
    const groups = (t.groups ?? []).join('\n');
    if (groups && groups !== emitted) {
      if (lines.at(-1) !== '') lines.push('');
      lines.push(...comment(groups).split('\n').map((l) => l.replace(/^ {2}/, '')));
    }
    emitted = groups;
    if (t.$description) lines.push(...comment(t.$description).split('\n').map((l) => l.replace(/^ {2}/, '')));
    lines.push(`export const ${t.jsName} = ${t.value};`);
  }
  lines.push(
    '',
    '/* Derived, not authored: the number of --color-cat-* slots in',
    ' * contracts/design/palette.dark.json. Assigned in order and NEVER cycled -- a 9th',
    ' * series folds to "Other", small multiples, or direct labels. */',
    `export const catSlots = ${await catSlotCount()};`,
  );
  const body = `${lines.join('\n')}\n`;
  return new Map(SCRIPT_TARGETS.map((path) => [path, body]));
}

export function designPath(source: string, on: PathModule = nodePath) {
  return toPosix(on.join(root, 'contracts/design', source), on);
}

export function isFrom(token: DtcgToken, source: string, on: PathModule = nodePath) {
  return typeof token.filePath === 'string'
    && nodePath.posix.basename(toPosix(token.filePath, on)) === source;
}

async function load(source: string) {
  const against = (RESOLVES_AGAINST as Record<string, string[]>)[source] ?? [];
  const sd = new StyleDictionary({
    source: [...against.map((s) => designPath(s)), designPath(source)],
    platforms: { css: { transforms: ['name/kebab'] } },
  }, { verbosity: 'silent' });
  const { tokens } = await sd.getPlatformTokens('css');
  return { tokens, from: source };
}

function comment(d: string) {
  if (!d.includes('\n')) return `  /* ${d} */`;
  return ['  /*', ...d.split('\n').map((l: string) => `     ${l}`), '   */'].join('\n');
}

function render(token: StampedToken) {
  const decl = `  --${emittedName(token)}:${referenceOf(token) ?? serialize(token)};`;
  const d = token.$description;
  if (!d) return decl;
  if (!d.includes('\n')) return `${decl} /* ${d} */`;
  return `${comment(d)}\n${decl}`;
}

function holdsA(node: DtcgNode, from: string): boolean {
  for (const [, child] of childEntries(node)) {
    if (isToken(child) ? isFrom(child, from) : holdsA(child, from)) return true;
  }
  return false;
}

type Emitted =
  | { group: false; token: StampedToken; groups: string[] }
  | { group: true; description: string };

const isTokenItem = (item: Emitted): item is Extract<Emitted, { group: false }> => !item.group;

function* walk({ tokens, from }: { tokens: any; from: string },
  groups: string[] = []): Generator<Emitted> {
  for (const [, child] of childEntries(tokens)) {
    if (isToken(child)) {
      if (isFrom(child, from) && isStamped(child)) yield { group: false, token: child, groups };
      continue;
    }
    if (!child.$description) { yield* walk({ tokens: child, from }, groups); continue; }
    if (!holdsA(child, from)) continue;
    yield { group: true, description: child.$description };
    yield* walk({ tokens: child, from }, [...groups, child.$description]);
  }
}

function renderLines(items: Emitted[]) {
  const lines = [];
  for (const item of items) {
    if (isTokenItem(item)) { lines.push(render(item.token)); continue; }
    if (lines.length) lines.push('');
    lines.push(comment(item.description));
  }
  return lines;
}

async function block({ selector, source }: { selector: string; source: string }) {
  const buckets = new Map<string, Emitted[]>([['', []]]);
  for (const item of walk(await load(source))) {
    const theme = isTokenItem(item) ? themeOf(item.token) : '';
    buckets.set(theme, [...(buckets.get(theme) ?? []), item]);
  }
  const base = buckets.get('') ?? [];
  const references = base.filter((item) => isTokenItem(item) && referenceOf(item.token));
  const out = base.length ? [`${selector}{\n${renderLines(base).join('\n')}\n}`] : [];

  for (const [theme, scope] of THEME_SCOPES) {
    const restated = references.length
      ? [`${scope(selector)}{\n${renderLines(references).join('\n')}\n}`] : [];
    const themed = buckets.get(theme) ?? [];
    const overrides = themed.length
      ? [`${scope(selector)}{\n${renderLines(themed).join('\n')}\n}`] : [];
    out.push(...restated, ...overrides);
  }
  return out.join('\n');
}

const CATALOGUE_NOTE = 'The extensions this build ships, as NAMES rather than as classes, because a\n'
  + 'consumer names one in arena.config.json and only a page composes the class from it. Derived\n'
  + 'from FILES in scripts/generate/arena/generate-tokens.ts rather than authored anywhere, so it\n'
  + 'can neither name an extension that paints nothing nor miss one that does; the name is read\n'
  + 'off the selector because the selector is what a page applies, and check:extensions is what\n'
  + 'holds the selector and the file to each other.\n'
  + '\n'
  + 'A token and not a list in a script: every surface that draws Arena already loads this sheet,\n'
  + 'so the catalogue is readable at any page depth with no fetch, and the control that cycles\n'
  + 'voices never has to be taught to tell an extension class from a palette one, which is a rule\n'
  + 'that would then exist twice. "none" is absent because it is the ABSENCE of an extension\n'
  + 'rather than one this build ships, and a reader prepends it for the same reason\n'
  + 'arena.config.json spells it out instead of omitting the field.\n'
  + '\n'
  + 'It carries no appearance, which is why check:coverage excludes it from the utility surface\n'
  + 'rather than looking for a namespace that could hold a list.';

function catalogueBlock(names: string[]) {
  return `:root{\n${comment(CATALOGUE_NOTE)}\n  --${CATALOGUE}:${names.join(',')};\n}`;
}

export async function buildAll() {
  const out = new Map();
  for (const file of FILES) {
    const blocks = [];
    for (const b of file.blocks) blocks.push(await block(b));
    const names = extensionsIn(file.blocks);
    if (names.length) blocks.push(catalogueBlock(names));
    out.set(file.out, `${HEADER}\n${blocks.join('\n')}\n`);
  }
  return out;
}

async function main() {
  const built = await buildAll();
  for (const [name, css] of built) {
    writeFileSync(join(root, 'contracts/design-generated', name), css);
    console.log(`build-tokens: wrote contracts/design-generated/${name}`);
  }
  const modules = await buildScriptModules();
  for (const [path, source] of modules) {
    writeFileSync(join(root, path), source);
    console.log(`build-tokens: wrote ${path}`);
  }
  writeFileSync(join(root, BREAKPOINT_TARGET), await buildBreakpointTheme());
  console.log(`build-tokens: wrote ${BREAKPOINT_TARGET}`);
}

if (isMainModule(import.meta.url)) await main();
