/* Writes the rules of the language into every surface that states them, from the one declaration
 * in language-rules.ts. Two of the three targets are Markdown and take a marked region a person
 * placed, on the argument generate-npm-pages.ts makes: where a section sits on a page is the
 * page's decision and only what it says belongs to a script. The third is context7.json, which
 * carries no comment syntax, so its rules array is replaced whole and the file is re-serialised.
 * Every entry of that array is held elsewhere to being a span of the router, which is why the
 * short half of a rule is emitted into both and why neither is written by hand. */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { isMainModule } from '../../utils/main-module.ts';
import { repoRoot as root } from '../../lib/arena/repo-root.ts';
import {
  RULES, renderList, renderShortList, renderHeldSentence,
} from '../../lib/arena/language-rules.ts';

export const ROUTER = 'skills/design/SKILL.md';
export const README = 'README.md';
export const CONTEXT7 = 'context7.json';

export const MARKED = [ROUTER, README];
export const TARGETS = [...MARKED, CONTEXT7];

export const node = {
  name: 'generate:rules',
  reads: ['scripts/lib/arena/language-rules.ts', ...TARGETS],
  writes: TARGETS,
  feeds: ['build:mcp-package', 'build:site', 'check:community', 'check:routes', 'check:rules',
    'check:support',
    'check:register'],
};

export const OPEN_LINE = '<!-- @language GENERATED by bun run generate:rules.'
  + ' Edit scripts/lib/arena/language-rules.ts, not this copy. -->';
export const CLOSE_LINE = '<!-- @language end -->';
export const OPENS_AT = /^<!-- @language GENERATED /;

export function renderRouterRegion(rules = RULES) {
  return [OPEN_LINE, '', renderHeldSentence(rules), '', renderList(rules), '', CLOSE_LINE].join('\n');
}

export function renderReadmeRegion(rules = RULES) {
  return [OPEN_LINE, '', renderShortList(rules), '', CLOSE_LINE].join('\n');
}

export const REGIONS: Record<string, (rules?: typeof RULES) => string> = {
  [ROUTER]: renderRouterRegion,
  [README]: renderReadmeRegion,
};

export function applyRegion(target: string, source: string, region: string) {
  const lines = source.split('\n');
  const from = lines.findIndex((line) => OPENS_AT.test(line));
  if (from === -1)
    throw new Error(
      `generate-rules: ${target} carries no @language region to write into. A person places the `
      + 'markers, because where the rules sit on a page is that page\'s decision and only what '
      + 'they say belongs to this script.',
    );
  const to = lines.indexOf(CLOSE_LINE, from);
  if (to === -1) throw new Error(`generate-rules: the @language region in ${target} opens and never closes`);
  return [...lines.slice(0, from), ...region.split('\n'), ...lines.slice(to + 1)].join('\n');
}

export function renderTarget(target: string, source: string, rules = RULES) {
  const render = REGIONS[target];
  if (!render) throw new Error(`generate-rules: no region is declared for ${target}`);
  return applyRegion(target, source, render(rules));
}

export function renderIndex(source: string, rules = RULES) {
  const config = JSON.parse(source);
  config.rules = rules.map((rule) => rule.short);
  return `${JSON.stringify(config, null, 2)}\n`;
}

export function writeRules({ base = root, read = readFileSync, write = writeFileSync } = {}) {
  const written = [];
  for (const target of TARGETS) {
    const path = join(base, target);
    const before = read(path, 'utf8') as string;
    const after = target === CONTEXT7 ? renderIndex(before) : renderTarget(target, before);
    if (after === before) continue;
    write(path, after);
    written.push(target);
  }
  return written;
}

function main() {
  const written = writeRules();
  for (const target of written) console.log(`generate-rules: wrote ${target}`);
  console.log(`generate-rules: ${RULES.length} rule(s) reach ${TARGETS.length} surface(s)`);
}

if (isMainModule(import.meta.url)) main();
