/* The half of an npm page that is the same page in both packages. Two documents with one file
 * name are one document rendered per layer, so what they share is a single source said twice: it
 * was said twice by hand, 8,700 characters of it, and the two had already drifted in wording
 * elsewhere on the page. Each region is emitted between markers a person placed, because where a
 * section sits on the page is the author's decision and only what it says is this file's.
 * Everything a layer decides, the import idiom, what the package exports and how a layout is
 * composed, stays hand-written in each. */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { isMainModule } from '../../utils/main-module.ts';
import { repoRoot as root } from '../../lib/arena/repo-root.ts';

export const TARGETS = [
  'frameworks/react/PACKAGE.md',
  'frameworks/angular/PACKAGE.md',
];

export const node = {
  name: 'generate:npm-pages',
  reads: [...TARGETS],
  writes: TARGETS,
  feeds: [
    'build:angular-package',
    'build:react-package',
    'check:arbitrary',
    'check:dimensions',
    'check:duplicate-constants',
    'check:generated',
    'check:icons',
    'check:layer-independence',
    'check:routes',
    'check:script-tokens',
    'check:skills', 'build:site'],
};

export const openLine = (key: string) => `<!-- @shared ${key} GENERATED by bun run generate:npm-pages.`
  + ' Edit that script, not this copy. -->';
export const closeLine = (key: string) => `<!-- @shared ${key} end -->`;
export const opensAt = (key: string) => new RegExp(`^<!-- @shared ${key} GENERATED `);

export const REGIONS: Record<string, (base?: string) => string> = {
  offer: () => `## What Arena gives a project

**Components whose API is a contract.** Every member of every component is declared once, in one
place both layers are generated from and held to, so a name, a type, a default and what it means
are the same under either framework, and the table documenting a component is emitted from that
declaration rather than written beside it.

**Behaviour each component binds rather than an audit somebody runs.** A component names the
accessibility pattern it implements, most of them a
[WAI-ARIA Authoring Practices](https://www.w3.org/WAI/ARIA/apg/patterns/) one: the roles it
carries, the keys it answers, where focus goes and what dismisses it. The pattern is recorded per
component, and so is anything a component does not yet meet, with its reason.

**A style kernel, which is how Arena stops looking like Arena.** Arena keeps the questions about
shape, space, weight and depth and ships one set of answers; a project writes its own as a style
plugin, which is the ordinary case rather than an escape hatch. A palette is not an appearance,
so the config below is the smaller half of that decision.

**A \`<head>\` for a product that has to be found from outside it, and it is optional.** Arena
writes it in the Angular layer, at \`@dravensoft/arena-angular/metadata\`: a title composed with
Angular's own, a description, a canonical and the \`og:*\` pair, and every route private until it
says otherwise. It sits behind a second entry point because reaching it means reaching
the router, an optional peer nothing else here asks for. \`@dravensoft/arena-react\` writes no
\`<head>\`, so a React project keeps that with whatever its own framework offers;
\`ArenaBreadcrumbs\` describes the trail it draws in \`schema.org\` terms under both.`,

  register: () => `## The screens it is for

Arena is a **product-application library**: its components are the furniture of an application
somebody works in, tables and their rows, forms and their fields, navigation, dialogs, charts,
cards and the empty, loading and error states around them. A media or a consumer product is a
different register, so a photo wall, a story ring, a feed of posts, a slideshow, a document
editor and a game map are markup you write yourself.

**The skin travels either way.** A style plugin answers every role whatever the product is, so
what Arena does draw wears your appearance rather than Arena's. What runs out first is the
component list.`,

  repository: () => `## This package ships the components and not the language

See it before you install it: **https://arena.dravensoft.org** has the guidelines, a kitchen sink
and a playground for every component. Source and full documentation:
**https://github.com/dravensoft-dev/arena**

**An agent building with Arena needs the repository, and this is a prerequisite rather than a
recommendation.** The rules every component answers to, the usage document of each one, and the
style kernel a project answers to make Arena look like its own product are all there and none of
them is in this tarball. Install the **Claude Code plugin**, or clone the repository and point your
agent at \`skills/design/SKILL.md\`, before you ask for the first screen. Over HTTP the same route
starts at **https://arena.dravensoft.org/llms.txt**.

Without them an agent guesses, and **no gate reads your application**, so nothing reports the
difference: the screen renders, and the rules it breaks are the ones only a reader notices.

The package is the code. The repository is the language.`,

  skin: () => `## Declare your skin

**A palette is not an appearance.** Arena keeps 72 questions about shape, space, weight and depth,
and the answers are a style plugin your project writes: the config below decides which colours a
surface takes and none of how round, how tight or how heavy the product is. That decision is paid
once per project and belongs before the first screen, and
\`skills/design/references/style-kernel.md\` in the repository is where it is made.

Write \`arena.config.json\` in your project root. This is the whole file, with one palette and
three fonts served by Google Fonts, and it is enough to start:

\`\`\`json
{
  "palettes": [
    {
      "name": "dark",
      "default": true,
      "polarity": "dark",
      "colors": {
        "base-100": "#141010",
        "base-200": "#1d1715",
        "base-300": "#241c19",
        "base-content": "#f3ede5",
        "primary": "#b52a20",
        "primary-content": "#ffffff",
        "secondary": "#c5a059",
        "secondary-content": "#141010",
        "neutral": "#2c221e",
        "neutral-content": "#d8cfc4",
        "info": "#3182ce",
        "info-content": "#141010",
        "success": "#38a169",
        "success-content": "#141010",
        "warning": "#ecc94b",
        "warning-content": "#141010",
        "error": "#e85151",
        "error-content": "#ffffff",
        "error-fill": "#ce3838",
        "cat-1": "#3c7b0a",
        "cat-2": "#3b63be",
        "cat-3": "#0a924b",
        "cat-4": "#6a59bc",
        "cat-5": "#00a3c0",
        "cat-6": "#884da9",
        "cat-7": "#00a99a",
        "cat-8": "#984697"
      }
    }
  ],
  "fonts": {
    "display": { "family": "Archivo", "src": "https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;700;800;900&display=swap" },
    "body": { "family": "Familjen Grotesk", "src": "https://fonts.googleapis.com/css2?family=Familjen+Grotesk:wght@400;500;600;700;800;900&display=swap" },
    "mono": { "family": "Spline Sans Mono", "src": "https://fonts.googleapis.com/css2?family=Spline+Sans+Mono:wght@400;500;600;700;800;900&display=swap" }
  }
}
\`\`\`

\`arena.config.example.json\` in this package is the same file with both Dravensoft palettes in
it, ready to copy and edit.

What each part means:

- **\`palettes\`** is an array, so declare as many as you want. Exactly one is the \`default\` and
  reaches \`:root\`; every other one becomes a class, \`.arena-<name>\`, that you put on
  \`<html>\` to switch skin.
- **\`polarity\`** is \`dark\` or \`light\`. It decides the native date picker's colour and it is
  what a first visit matches \`prefers-color-scheme\` against.
- **\`colors\`** takes all 27 keys above. \`error-fill\` is the only optional one: leave it out and
  Arena darkens \`error\` in oklab for the single filled danger surface it has.
- **\`cat-1\`** through **\`cat-8\`** are the chart ramp. Their order is their identity, so slot 3
  is always slot 3, and they are never used to mean anything, only to tell series apart.
- **\`fonts\`** fills the three families Arena reads. \`src\` takes either a stylesheet URL, as
  above, or a font binary you host yourself, which becomes an \`@font-face\`:
  \`{ "family": "Archivo", "src": "/fonts/archivo.woff2", "weight": "400 900" }\`.
- **\`stylesheet\`** is optional and names what you render, so you send nothing else. See
  Build to production, below.
- **\`stylePlugins\`** names the appearance, and it is optional only in the sense that leaving it
  out keeps somebody else's. It is a list, because a build can carry more than one register, and the first entry is what a page with no class on it looks
  like; every later one emits under \`.arena-<name>\` and is a difference. An entry is the word
  \`default\`, which is the appearance this package installs with, or a path to a directory of
  your own holding \`plugin.tokens.json\` and optionally \`plugin.css\`. The first entry answers
  every role Arena declares, and the command refuses one that does not: a custom property with no
  value is invalid at computed-value time, so an unanswered role is a missing border rather than
  a plainer look. Declare a list without \`default\` and you do not receive its stylesheet, the
  same way the preflight can already be dropped.
- **\`gradientMark\`** is optional, a boolean, and says the mark your product is drawn with is a
  gradient. Arena ships no element that is one, so yours lives in your own CSS, where \`--audit\`
  reports it: the scope reads which directory a line sits in, which is right for a part hook and
  wrong for a brand. Declare it once and that rule goes quiet in your sources; the colours inside
  the gradient are still reported, since they are the skin. It replaces an \`arena-audit allow\`
  marker, which silences every rule on its line and is repeated wherever the mark is drawn.

**A plugin carrying a \`plugin.css\` gets a third generated file**, \`plugin.generated.css\`, and
you import it beside the other two. It declares the cascade layer order itself and then opens
the reserved layer, so where your bundler places it among your other stylesheets cannot change
what wins.`,

  tail: () => `## Why might this package's latest version not match Arena's latest version?

[Why are the published package versions not identical?](https://github.com/dravensoft-dev/arena/blob/main/.github/workflows/AGENTS.md#why-are-the-published-package-versions-not-identical)

## License

MIT. See the repository.`,
};

export function renderRegion(key: string, base = root) {
  const render = REGIONS[key];
  if (!render) throw new Error(`generate-npm-pages: no region called ${key}`);
  return [openLine(key), '', render(base), '', closeLine(key)].join('\n');
}

export function applyRegion(source: string, key: string, region: string) {
  const lines = source.split('\n');
  const from = lines.findIndex((line) => opensAt(key).test(line));
  if (from === -1)
    throw new Error(
      `generate-npm-pages: no @shared ${key} region to write into. A person places the markers, `
      + 'because where a section sits on a page a consumer reads is the page\'s decision and only '
      + 'what the section says belongs to this script.',
    );
  const to = lines.indexOf(closeLine(key), from);
  if (to === -1) throw new Error(`generate-npm-pages: the @shared ${key} region opens and never closes`);
  return [...lines.slice(0, from), ...region.split('\n'), ...lines.slice(to + 1)].join('\n');
}

export function renderTarget(source: string, base = root) {
  return Object.keys(REGIONS).reduce(
    (text, key) => applyRegion(text, key, renderRegion(key, base)), source,
  );
}

export function writePages({ base = root, read = readFileSync, write = writeFileSync } = {}) {
  const written = [];
  for (const target of TARGETS) {
    const path = join(base, target);
    const before = read(path, 'utf8');
    const after = renderTarget(before, base);
    if (after === before) continue;
    write(path, after);
    written.push(target);
  }
  return written;
}

function main() {
  const written = writePages();
  for (const target of written) console.log(`generate-npm-pages: wrote ${target}`);
  console.log(`generate-npm-pages: ${TARGETS.length} page(s) carry ${Object.keys(REGIONS).length} shared region(s) each`);
}

if (isMainModule(import.meta.url)) main();
