/* Emits the playground into every framework layer from one source. The codec is copied
 * rather than reimplemented per layer, because two hand-written copies of decode() that
 * drift render the SAME url differently in each layer, which is the one failure this whole
 * arrangement exists to prevent, and no gate would see it: each layer would compile, each
 * suite would pass, and only a person comparing two pages would notice. */

import { readFileSync, readdirSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { isMainModule } from '../../utils/main-module.ts';
import { readJson } from '../../utils/read-file.ts';
import { toPosix } from '../../utils/posix-path.ts';
import { repoRoot as root } from '../../lib/arena/repo-root.ts';
import { kebab } from '../../utils/case.ts';
import { playgroundModel } from '../../lib/arena/playground-model.ts';
import type { Place, Places, PlaygroundModel } from '../../lib/arena/playground-model.ts';
import { reactEntry, reactPage } from '../../lib/react/playground-react.ts';
import { angularEntry, angularPage, MARKERS_SOURCE } from '../../lib/angular/playground-angular.ts';

export const PLAYGROUND_LAYERS = ['react', 'angular'];

export const PROBED_LAYERS = [...PLAYGROUND_LAYERS, 'tailwind'];

export const CODEC_SOURCE = 'frameworks/demos/PlaygroundCodec.ts';

export const node = {
  name: 'generate:playgrounds',
  reads: [
    CODEC_SOURCE, 'frameworks/demos/*.demo.json', 'frameworks/Components.json',
    'frameworks/angular/ProjectionMarkers.ts', 'contracts/api/types', 'contracts/api/components',
    ...PROBED_LAYERS.flatMap((layer) => ['ts', 'tsx', 'manifest.json']
      .map((ext) => `frameworks/${layer}/components/**/*.${ext}`)),
    '!frameworks/**/*.generated.*',
  ],
  writes: PLAYGROUND_LAYERS.flatMap((layer) => [
    `frameworks/${layer}/playground/PlaygroundCodec.generated.ts`,
    `frameworks/${layer}/components/**/*.demo.generated.html`,
    `frameworks/${layer}/components/**/*.demo.entry.generated.${layer === 'react' ? 'tsx' : 'ts'}`,
  ]),
  feeds: [
    'build:angular-demo',
    'build:angular-package',
    'build:angular-tests',
    'build:demos',
    'build:react-package',
    'check:angular',
    'check:angular-demos',
    'check:api',
    'check:appearance',
    'check:parts',
    'check:arbitrary',
    'check:behaviour',
    'check:compliance',
    'check:demos',
    'check:dimensions',
    'check:duplicate-constants',
    'check:focus-trap',
    'check:generated',
    'check:icons',
    'check:layer-independence',
    'check:playgrounds',
    'check:react-types',
    'check:script-tokens',
    'check:shared-arithmetic',
    'check:skills',
    'check:states',
    'build:site',
  ],
};

export const CODEC_BANNER =
  '/* GENERATED by scripts/generate/arena/generate-playgrounds.ts from frameworks/demos/PlaygroundCodec.ts.\n'
  + ' * Edit the source, not this copy: every layer carries the same bytes so the same URL cannot\n'
  + ' * resolve to two different views. */\n';

export function codecTarget(layer: string) {
  return toPosix(join('frameworks', layer, 'playground', 'PlaygroundCodec.generated.ts'));
}

export function renderCodec(source: string) {
  return `${CODEC_BANNER}\n${source}`;
}

export function codecFiles(base = root) {
  const source = readFileSync(join(base, CODEC_SOURCE), 'utf8');
  const body = renderCodec(source);
  return new Map(PLAYGROUND_LAYERS.map((layer) => [codecTarget(layer), body]));
}

export const PAGE_BANNER =
  '<!-- GENERATED by scripts/generate/arena/generate-playgrounds.ts. '
  + 'Edit the contract or the fixture, not this file. -->\n';

export const ENTRY_BANNER =
  '/* GENERATED by scripts/generate/arena/generate-playgrounds.ts from the component\'s API\n'
  + ' * contract and its frameworks/demos/ fixture. Edit one of those, not this file. */\n';

export function loadTypes(base = root) {
  const dir = join(base, 'contracts/api/types');
  const out = new Map();
  for (const file of readdirSync(dir).sort()) {
    if (!file.endsWith('.json')) continue;
    const type = readJson(join(dir, file));
    out.set(type.name, type);
  }
  return out;
}

export function loadContracts(base = root) {
  const dir = join(base, 'contracts/api/components');
  const out = new Map();
  for (const file of readdirSync(dir).sort()) {
    if (!file.endsWith('.json')) continue;
    out.set(file.replace(/\.json$/, ''), readJson(join(dir, file)));
  }
  return out;
}

export function loadPlaces(base = root) {
  const categories = readJson(join(base, 'frameworks/Components.json'));
  const out = new Map();
  for (const [category, names] of Object.entries(categories) as [string, string[]][]) {
    for (const name of names) out.set(name, { name, category, dir: kebab(name) });
  }
  return out;
}

export function placesFor(model: Pick<PlaygroundModel, 'component' | 'uses'>,
  all: Map<string, Place>): Places {
  const out = new Map();
  for (const name of [model.component, ...model.uses]) {
    const place = all.get(name);
    if (!place) throw new Error(`generate-playgrounds: ${model.component} reaches ${name}, which frameworks/Components.json does not name`);
    out.set(name, { ...place, self: name === model.component });
  }
  return out;
}

export function allComponents(base = root) {
  return [...loadContracts(base).keys()].sort();
}

export function componentFiles(base = root, components = allComponents(base)) {
  const contracts = loadContracts(base);
  const fixtures = new Map();
  for (const name of components) {
    fixtures.set(name, readJson(join(base, 'frameworks/demos', `${name}.demo.json`)));
  }
  const types = loadTypes(base);
  const all = loadPlaces(base);
  const markers = readFileSync(join(base, MARKERS_SOURCE), 'utf8');

  const files = new Map();
  for (const name of components) {
    const contract = contracts.get(name);
    const model = playgroundModel(contract, fixtures.get(name), types);
    const places = placesFor(model, all);
    const place = all.get(name);
    const dir = toPosix(join('frameworks', '<layer>', 'components', place.category, place.dir));

    const reactDir = dir.replace('<layer>', 'react');
    files.set(`${reactDir}/${name}.demo.generated.html`, reactPage(model, PAGE_BANNER));
    files.set(`${reactDir}/${name}.demo.entry.generated.tsx`, reactEntry(model, places, ENTRY_BANNER));

    const angularDir = dir.replace('<layer>', 'angular');
    files.set(`${angularDir}/${name}.demo.generated.html`, angularPage(model, PAGE_BANNER));
    files.set(`${angularDir}/${name}.demo.entry.generated.ts`, angularEntry(model, places, contracts, markers, ENTRY_BANNER));
  }
  return files;
}

export function buildPlaygrounds(base = root, components = allComponents(base)) {
  const files = new Map([...codecFiles(base), ...componentFiles(base, components)]);
  const problems = [];
  if (files.size === 0) {
    problems.push('generate-playgrounds: emitted 0 files, and an empty emit is a failure rather than a clean pass');
  }
  return { files, problems };
}

function main() {
  const { files, problems } = buildPlaygrounds();
  if (problems.length > 0) {
    for (const problem of problems) console.error(problem);
    process.exit(1);
  }
  for (const [rel, body] of files) {
    const path = join(root, rel);
    if (!existsSync(dirname(path))) mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, body);
    console.log(`wrote ${rel}`);
  }
  console.log(`generate-playgrounds: ${files.size} file(s) emitted`);
}

if (isMainModule(import.meta.url)) main();
