/* Emits the kitchen-sink page into every framework layer from one arrangement per design
 * extension. It exists for the same reason generate-playgrounds.ts does, one turn further on:
 * the playground pages are already the same page in both layers, and nothing compares what they
 * paint. These pages are what a comparison can be run over, so the one thing they may never be
 * is authored twice. A page written per layer would drift in its section order or in its seed,
 * and a difference in the frame reads as a difference in a component, which is the single
 * failure check:pixel-parity exists to see and the single failure it must never invent. */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { isMainModule } from '../../utils/main-module.ts';
import { readJson } from '../../utils/read-file.ts';
import { toPosix } from '../../utils/posix-path.ts';
import { repoRoot as root } from '../../lib/arena/repo-root.ts';
import { PAGE_FILE, entryFile } from '../../lib/arena/kitchen-sink-page.ts';
import { sinkModel, placesFor, stagedComponents, NONE } from '../../lib/arena/kitchen-sink-model.ts';
import type { SinkFixture } from '../../lib/arena/kitchen-sink-model.ts';
import { UP as PLAYGROUND_UP } from '../../lib/arena/playground-page.ts';
import { loadPlaces, loadContracts } from './generate-playgrounds.ts';
import { reactSinkEntry, reactSinkPage, UP as SINK_UP } from '../../lib/react/kitchen-sink-react.ts';
import { angularSinkEntry, angularSinkPage, MARKERS_SOURCE } from '../../lib/angular/kitchen-sink-angular.ts';

export const SINK_LAYERS = ['react', 'angular'];

export const FIXTURES = 'frameworks/kitchen-sink';

export const EXTENSION_PARTIALS = 'contracts/design';

export const node = {
  name: 'generate:kitchen-sink',
  reads: [
    `${FIXTURES}/*.sink.json`, 'frameworks/demos/*.demo.json', 'frameworks/Components.json',
    'frameworks/angular/ProjectionMarkers.ts', 'contracts/api/components',
    `${EXTENSION_PARTIALS}/extension.*.json`, 'frameworks/tailwind/components/**/*.manifest.json',
  ],
  writes: SINK_LAYERS.flatMap((layer) => [
    `frameworks/${layer}/kitchen-sink/**/${PAGE_FILE}`,
    `frameworks/${layer}/kitchen-sink/**/*.sink.entry.generated.${layer === 'react' ? 'tsx' : 'ts'}`,
  ]),
  feeds: [
    'build:angular-demo',
    'build:angular-package',
    'build:angular-tests',
    'build:demos',
    'build:react-package',
    'check:angular',
    'check:arbitrary',
    'check:demos',
    'check:dimensions',
    'check:duplicate-constants',
    'check:generated',
    'check:icons',
    'check:kitchen-sink',
    'check:layer-independence',
    'check:pixel-parity',
    'check:react-types',
    'check:script-tokens',
    'check:skills',
    'build:site',
  ],
};

export const PAGE_BANNER =
  '<!-- GENERATED by scripts/generate/arena/generate-kitchen-sink.ts. '
  + 'Edit the arrangement in frameworks/kitchen-sink/, not this file. -->\n';

export const ENTRY_BANNER =
  '/* GENERATED by scripts/generate/arena/generate-kitchen-sink.ts from the extension\'s\n'
  + ' * arrangement and each component\'s frameworks/demos/ fixture. Edit one of those. */\n';

export function shippedExtensions(base = root) {
  const dir = join(base, EXTENSION_PARTIALS);
  const found = readdirSync(dir)
    .filter((file) => file.startsWith('extension.') && file.endsWith('.json'))
    .map((file) => file.slice('extension.'.length, -'.json'.length))
    .sort();
  return [NONE, ...found];
}

export function loadFixtures(base = root): Map<string, SinkFixture> {
  const dir = join(base, FIXTURES);
  const out = new Map<string, SinkFixture>();
  for (const file of readdirSync(dir).sort()) {
    if (!file.endsWith('.sink.json')) continue;
    const fixture = readJson(join(dir, file)) as SinkFixture;
    const named = file.slice(0, -'.sink.json'.length);
    if (fixture.extension !== named) {
      throw new Error(`generate-kitchen-sink: ${file} declares extension "${fixture.extension}", and the `
        + 'file is named for another, so the page it emits would land under a voice it is not painted in');
    }
    out.set(named, fixture);
  }
  return out;
}

export function loadDemos(base = root) {
  const dir = join(base, 'frameworks/demos');
  const out = new Map();
  for (const file of readdirSync(dir).sort()) {
    if (!file.endsWith('.demo.json')) continue;
    out.set(file.slice(0, -'.demo.json'.length), readJson(join(dir, file)));
  }
  return out;
}

export function pageDir(layer: string, extension: string) {
  return toPosix(join('frameworks', layer, 'kitchen-sink', extension));
}

export function buildKitchenSink(base = root) {
  const fixtures = loadFixtures(base);
  const demos = loadDemos(base);
  const places = loadPlaces(base);
  const contracts = loadContracts(base);
  const markers = readFileSync(join(base, MARKERS_SOURCE), 'utf8');
  const staged = stagedComponents([...places.keys()], base);

  const files = new Map<string, string>();
  for (const [extension, fixture] of fixtures) {
    const model = sinkModel(fixture, demos, staged, { from: PLAYGROUND_UP, to: SINK_UP });
    const where = placesFor(model, places);

    const reactDir = pageDir('react', extension);
    files.set(`${reactDir}/${PAGE_FILE}`, reactSinkPage(model, PAGE_BANNER));
    files.set(`${reactDir}/${entryFile(extension, 'tsx')}`, reactSinkEntry(model, where, ENTRY_BANNER));

    const angularDir = pageDir('angular', extension);
    files.set(`${angularDir}/${PAGE_FILE}`, angularSinkPage(model, PAGE_BANNER));
    files.set(`${angularDir}/${entryFile(extension, 'ts')}`,
      angularSinkEntry(model, where, contracts, markers, ENTRY_BANNER));
  }

  const problems = [];
  if (files.size === 0) {
    problems.push('generate-kitchen-sink: emitted 0 files, and an empty emit is a failure rather than a clean pass');
  }
  const shipped = shippedExtensions(base);
  for (const extension of shipped) {
    if (!fixtures.has(extension)) {
      problems.push(`generate-kitchen-sink: the build ships the ${extension} voice and `
        + `${FIXTURES}/${extension}.sink.json is not there, so that voice gets no page and nothing compares it`);
    }
  }
  for (const extension of fixtures.keys()) {
    if (!shipped.includes(extension)) {
      problems.push(`generate-kitchen-sink: ${extension}.sink.json arranges a voice the build does not ship, `
        + 'so its page would paint a scope class the cascade ignores and read as the plain voice');
    }
  }
  return { files, problems };
}

function main() {
  const { files, problems } = buildKitchenSink();
  if (problems.length > 0) {
    for (const problem of problems) console.error(problem);
    process.exit(1);
  }
  for (const [rel, body] of files) {
    const path = join(root, rel);
    if (!existsSync(dirname(path))) mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, body);
    console.log(`wrote ${rel}`);
  }
  console.log(`generate-kitchen-sink: ${files.size} file(s) emitted`);
}

if (isMainModule(import.meta.url)) main();
