/* Downloads the three variable webfonts Arena self-hosts and writes the @font-face sheet
 * plus the record that holds each binary to its hash. A Face is one of them: the family,
 * the weight range the variable binary covers, and the file under assets/fonts/. */

import { writeFileSync, mkdirSync, readFileSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { readJson } from '../../utils/read-file.ts';
import { repoRoot as root } from '../../lib/arena/repo-root.ts';
import { fontWeights, googleFontsUrl } from '../../lib/core/arena-config.ts';
import { childEntries } from '../../lib/core/dtcg-shapes.ts';
import { byKey } from '../../utils/compare.ts';

type Face = { family: string; weight: [number, number]; file: string };

const fontsDir = join(root, 'assets', 'fonts');
const cssPath = join(root, 'contracts', 'design-generated', 'fonts.generated.css');

export const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0 Safari/537.36';

export function families(root: string) {
  const src = readJson(join(root, 'contracts/design/typography.json'));
  const weights = fontWeights(root);
  return childEntries(src.font)
    .map(([, token]) => {
      const css = token.$value[0];
      return { css, slug: css.toLowerCase().replace(/\s+/g, '-'), weights };
    });
}

async function google(css: string, weights: number[]) {
  const url = googleFontsUrl(css, weights);
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`CSS fetch failed for ${css}: ${res.status}`);
  return res.text();
}

function latinFaces(cssText: string) {
  const faces = [];
  const re = /\/\*\s*latin\s*\*\/\s*@font-face\s*{([^}]*)}/g;
  let m;
  while ((m = re.exec(cssText)) !== null) {
    const block = m[1];
    const weight = /font-weight:\s*(\d+)/.exec(block ?? '')?.[1];
    const src = /src:\s*url\(([^)]+\.woff2)\)/.exec(block ?? '')?.[1];
    if (weight && src) faces.push({ weight: Number(weight), src });
  }
  return faces;
}

async function download(url: string) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`binary fetch failed: ${url} ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

export function fontsCss(faces: Face[]) {
  const header =
    `/* contracts/design-generated/fonts.generated.css — self-hosted, CSP-clean webfonts.\n` +
    `   GENERATED by scripts/generate/core/fetch-fonts.ts; edit that, not this. Binaries live in\n` +
    `   assets/fonts/, which carry no .generated. infix: they are binary and need the\n` +
    `   network to reproduce. One file per family, not one per weight: all three are VARIABLE\n` +
    `   fonts and Google serves one binary covering the whole range, so a face per weight wrote\n` +
    `   the same bytes under a dozen names. Families match contracts/design-generated/typography.generated.css\n` +
    `   (Archivo / Familjen Grotesk / Spline Sans Mono). */\n`;
  const rules = faces.map(({ family, weight, file }) =>
    `@font-face {\n` +
    `  font-family: '${family}';\n` +
    `  font-style: normal;\n` +
    `  font-weight: ${Array.isArray(weight) ? weight.join(' ') : weight};\n` +
    `  font-display: swap;\n` +
    `  src: url('../../assets/fonts/${file}') format('woff2');\n` +
    `}`);
  return `${header}\n${rules.join('\n\n')}\n`;
}

export const FONTS = 'assets/fonts/Fonts.generated.json';

export function faceRecord(faces: Face[], root: string) {
  const out: Record<string, unknown> = {};
  for (const { family, weight, file } of [...faces].sort(byKey((face) => face.file))) {
    out[file] = {
      family,
      weights: weight,
      sha256: createHash('sha256').update(readFileSync(join(root, 'assets', 'fonts', file))).digest('hex'),
    };
  }
  return out;
}

export function recordProblems(record: Record<string, unknown>, present: string[],
  hashOf: (file: string) => string) {
  const problems = [];
  const recorded = Object.entries(record) as [string, { sha256: string; weights: [number, number] }][];
  for (const [file, entry] of recorded) {
    if (!present.includes(file)) {
      problems.push(`${file}: recorded in ${FONTS} and not present in assets/fonts/ -- a clone behind a firewall cannot re-download it, so a missing binary is a broken checkout rather than a rebuildable one`);
      continue;
    }
    const actual = hashOf(file);
    if (actual !== entry.sha256) problems.push(`${file}: sha256 ${actual}, recorded ${entry.sha256} -- the binary on disk is not the one this repository shipped`);
    const [min, max] = entry.weights;
    if (!(Number.isInteger(min) && Number.isInteger(max) && min < max)) {
      problems.push(`${file}: records the weight range [${entry.weights}] -- a variable face needs a real min and max, and the CSS declares whatever is here`);
    }
  }
  for (const file of present) {
    if (!(file in record)) problems.push(`${file}: present in assets/fonts/ and not recorded in ${FONTS} -- run fetch-fonts.ts, or delete it`);
  }
  return problems;
}

export function facesFromDisk(root: string): Face[] {
  const present = new Set(readdirSync(join(root, 'assets', 'fonts')));
  let recorded;
  try {
    recorded = readJson(join(root, FONTS));
  } catch {
    recorded = {};
  }
  const faces: Face[] = [];
  for (const fam of families(root)) {
    const file = `${fam.slug}.woff2`;
    if (!present.has(file) || !recorded[file]) {
      throw new Error(`no assets/fonts/${file} for "${fam.css}" — run bun scripts/generate/core/fetch-fonts.ts without --css-only`);
    }
    faces.push({ family: fam.css, weight: recorded[file].weights, file });
  }
  return faces;
}

export function weightRange(weights: number[]): [number, number] {
  const numbers = weights.map(Number).sort((a, b) => a - b);
  return [numbers[0] ?? 0, numbers[numbers.length - 1] ?? 0];
}

async function main() {
  mkdirSync(fontsDir, { recursive: true });
  const faces: Face[] = [];
  for (const fam of families(root)) {
    const cssText = await google(fam.css, fam.weights);
    const googleFaces = latinFaces(cssText);
    if (googleFaces.length === 0) throw new Error(`no latin face for "${fam.css}"`);
    const sources = new Set(googleFaces.map((f) => f.src));
    if (sources.size !== 1) {
      throw new Error(
        `"${fam.css}" served ${sources.size} distinct binaries across ${googleFaces.length} weights, so it is not the `
        + 'single variable file this generator writes. Restore a face per weight before shipping it.',
      );
    }
    const file = `${fam.slug}.woff2`;
    const [face] = googleFaces;
    if (!face) throw new Error(`fetch-fonts: Google returned no @font-face for ${file}`);
    writeFileSync(join(fontsDir, file), await download(face.src));
    const served = googleFaces.map((f) => Number(f.weight));
    faces.push({ family: fam.css, weight: weightRange(served), file });
    console.log(`${fam.css}: one variable file covering ${served.length} served weight(s)`);
  }

  writeFileSync(cssPath, fontsCss(faces));
  console.log('wrote contracts/design-generated/fonts.generated.css');
  writeFileSync(join(root, FONTS), `${JSON.stringify(faceRecord(faces, root), null, 2)}\n`);
  console.log(`wrote ${FONTS}`);
}

if (import.meta.main) {
  if (process.argv.includes('--css-only')) {
    writeFileSync(cssPath, fontsCss(facesFromDisk(root)));
    console.log('wrote contracts/design-generated/fonts.generated.css (no download)');
  } else {
    await main();
  }
}
