/* Holds the .generated. convention: a script under scripts/ writes the file, and the
 * name says so. Both directions fail silently otherwise -- an output without the infix
 * is read as hand-written by check:docs, and a payload file caught by an ignore pattern
 * ships a tag whose intro/styles.css @imports resolve to nothing, with no error. */

import { readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { hostBinary } from '../../lib/arena/host-binary.ts';
import { join } from 'node:path';
import { globToRegExp } from '../../utils/text.ts';
import { relPosix } from '../../utils/posix-path.ts';
import { isMainModule } from '../../utils/main-module.ts';
import { walkFiles } from '../../utils/walk-files.ts';
import { findComments } from '../../lib/arena/comments.ts';
import { repoRoot as ROOT } from '../../lib/arena/repo-root.ts';

export const node = {
  name: 'check:generated',
  reads: [
    '.gitignore', 'frameworks/**', 'contracts/design/**', 'contracts/design-generated/**',
    'intro/**', 'assets/fonts/**',
    '!frameworks/react/dist/**', '!frameworks/angular/dist/**', '!frameworks/angular/build/**',
  ],
  writes: [],
  feeds: [],
};


const SCANNED_EXTENSIONS = ['.mjs', '.jsx', '.tsx', '.ts', '.js', '.css'];
const SKIPPED_DIRECTORIES = new Set(['node_modules', '.git', 'build', 'dist', '.cache']);

export const UNMARKED = {
  'intro/support.js':
    'generated by dc-runtime, whose source is not in this repository, so a clone cannot '
    + 'rebuild it. Not reproducible means never ignorable, and the infix would promise a '
    + '`bun run build` that cannot deliver it.',
  'assets/fonts/*.woff2':
    'downloaded from Google Fonts by scripts/generate/core/fetch-fonts.ts. Binary, so it '
    + 'carries no header, and reproducing it needs the network. The one generated output '
    + 'identified by its generator rather than by its name.',
};

export const UNTRACKED = {
  'frameworks/react/vendor/*.generated.js':
    'a 975 KB CommonJS->ESM bundle of a devDependency, read only by the demo pages\' importmap.',
  'frameworks/react/components/**/*.generated.js':
    'the compiled sibling of a component source, read only by a demo page.',
  'frameworks/react/ui-kits/**/*.generated.js':
    'the same, for the Delivery Console example app.',
  'frameworks/react/components/**/*.demo.entry.generated.tsx':
    'a demo entry, emitted from the component\'s API contract and its frameworks/demos/ fixture. '
    + 'The page beside it loads the compiled sibling; check:playgrounds holds both to a fresh run '
    + 'and holds the two layers to one model.',
  'frameworks/angular/components/**/*.demo.entry.generated.ts': 'the same file, emitted into the other layer.',
  'frameworks/react/playground/PlaygroundCodec.generated.ts':
    'the URL codec, emitted into every layer from frameworks/demos/PlaygroundCodec.ts so the same '
    + 'link cannot resolve to two different views. check:playgrounds holds each copy to the source.',
  'frameworks/angular/playground/PlaygroundCodec.generated.ts': 'the same file, emitted into the other layer.',
  'frameworks/react/playground/*.generated.js':
    'the same, for the harness every generated demo page mounts. It is not part of the package: '
    + 'tsconfig.dist.json excludes the directory and no barrel exports it.',
  'frameworks/react/DataVisuals.generated.js':
    'a compiled layer-root helper a demo page loads. A browser cannot execute TypeScript, so a '
    + 'page importing one needs it compiled.',
  'frameworks/react/AnchorActivation.generated.js':
    'the same, for the predicate that decides which activation of an anchor is the router\'s.',
  'frameworks/react/Theme.generated.js': 'the same, for the theme helper.',
  'frameworks/react/WarnOnce.generated.js': 'the same, for the once-per-message console warning '
    + 'the charts and ArenaTable share.',
  'frameworks/react/UseArenaContainerWidth.generated.js': 'the same, for the container-width hook.',
  'frameworks/react/UseDialogModal.generated.js': 'the same, for the modal focus helper.',
  'frameworks/react/components/**/*.manifest.generated.ts':
    'the shared recipe for one component, emitted into the layer that renders it. The manifest is '
    + 'authored once as JSON under frameworks/tailwind/ and emitted per layer for the reason the '
    + 'script tokens are: a component\'s import then never crosses a layer boundary. '
    + 'check:tailwind-generated holds every copy to a fresh compile of the one source.',
  'frameworks/react/Tv.generated.ts':
    'the configured tailwind-variants instance both layers resolve a manifest through, emitted '
    + 'beside the manifests for the same reason and held to its source by the same gate.',
  'frameworks/react/Tv.generated.js': 'the compiled sibling of that, which a demo page loads.',
  'frameworks/react/Index.generated.ts':
    'the layer entry point, derived from the component directories. The package build compiles '
    + 'it and emits its declaration, so the only reader outside this repository is a tarball.',
  'frameworks/react/Api.generated.ts':
    'the contract types, emitted per layer from contracts/api/types/ so a component\'s import '
    + 'never crosses the boundary. check:api holds it to the contracts.',
  'frameworks/angular/Api.generated.ts': 'the same file, emitted into the other layer.',
  'frameworks/react/Tokens.generated.js':
    'the design values JavaScript reads as numbers rather than through CSS, emitted from '
    + 'contracts/design/. check:script-tokens holds it to the source and to the CSS.',
  'frameworks/angular/Tokens.generated.ts': 'the same values, emitted into the other layer.',
  'frameworks/tailwind/components/**/*.manifest.generated.ts':
    'a manifest re-emitted as a typed module, which is the form a variants recipe imports. '
    + 'check:tailwind-generated holds each to a fresh compile of its .manifest.json.',
  'frameworks/tailwind/Breakpoints.generated.css':
    'the bp tokens as Tailwind breakpoint literals, which is the only form a media query can '
    + 'hold, since its condition takes no var(). Theme.css imports it and an adopter compiles '
    + 'their own utilities from that preset, so nothing outside this repository reads the file.',
  'frameworks/tailwind/Utilities.generated.css':
    'the compiled utility layer, read only by the specimen pages. An adopter imports '
    + 'frameworks/angular/theme/arena-tailwind.css and compiles their own.',
  'frameworks/tailwind/consume/components/**/*.styles.generated.css':
    'the CSS one component renders, compiled from its manifest through @apply and stripped of '
    + 'every Tailwind theme indirection, so no adopter property can reach in. It sits under '
    + 'consume/ rather than beside its manifest because every layer links THIS file: the whole '
    + 'directory is the one consumption surface, so no copy of it can disagree with another. '
    + 'The package build collects these into css/components/; check:component-css holds each to '
    + 'the manifest it came from.',
  'frameworks/tailwind/consume/Components.generated.css':
    'the barrel of every component sheet, in one import, which is what a page drawing most of '
    + 'the library links and what the package ships as css/components.css. A page that draws a '
    + 'handful links those sheets instead, which is what makes it pay for what it renders.',
  'frameworks/tailwind/consume/Preflight.generated.css':
    'Tailwind\'s preflight on its own, lifted out of the compiled sheet. A specimen and a playground '
    + 'need it for the same reason a package does: without the `font: inherit` it carries, a form '
    + 'control falls back to the browser\'s own size and every measurement around it moves.',
  'frameworks/tailwind/consume/Prelude.generated.css':
    'the @property registrations, the layer order and the keyframes every component sheet '
    + 'depends on, which is why each one imports it rather than documenting it: without the '
    + 'registrations every border and the focus ring are invalid at computed-value time.',
  'frameworks/tailwind/components/**/*.classes.generated.ts':
    'the manifest with each class string replaced by the Arena class name that draws it, which '
    + 'is what a component composes at runtime now that nothing merges utilities.',
  'frameworks/react/components/**/*.classes.generated.ts': 'the same file, emitted into the layer that renders it.',
  'frameworks/angular/components/**/*.classes.generated.ts': 'the same file, emitted into the other layer.',
  'frameworks/react/ArenaStyles.generated.ts':
    'the twenty-line factory that composes those names, emitted per layer so a component\'s '
    + 'import never crosses a boundary. It replaces the two runtime dependencies outright.',
  'frameworks/angular/ArenaStyles.generated.ts': 'the same file, emitted into the other layer.',
  'frameworks/react/ArenaStyles.generated.js': 'the compiled sibling of that, which a demo page loads.',
};

function walk(dir: string, root: string): string[] {
  return walkFiles(dir, { skip: (name) => name.startsWith('.') || SKIPPED_DIRECTORIES.has(name) })
    .filter((full) => SCANNED_EXTENSIONS.some((e) => full.endsWith(e)))
    .map((full) => relPosix(root, full));
}

function startsFile(source: string, comment: { text: string }) {
  return source.slice(0, source.indexOf(comment.text)).trim() === '';
}

export function claimsGeneration(source: string) {
  const [first] = findComments(source);
  return Boolean(first) && startsFile(source, first ?? { text: '' }) && /GENERATED (by|from)/i.test(first?.text ?? '');
}

export function unmarkedProblems(root = ROOT) {
  const problems = [];
  for (const rel of walk(root, root)) {
    if (rel.includes('.generated.')) continue;
    if (Object.hasOwn(UNMARKED, rel)) continue;
    if (claimsGeneration(readFileSync(join(root, rel), 'utf8'))) {
      problems.push(`${rel}: its header says a script writes it, but its name does not — rename it to *.generated.* or argue for it in UNMARKED`);
    }
  }
  return problems;
}

export function trackingProblems(root = ROOT, run = gitRun) {
  const tracked = new Set(run(['ls-files'], root));
  const problems = [];
  const claimed = new Set();

  for (const rel of walk(root, root)) {
    if (!rel.includes('.generated.')) continue;
    const pattern = run(['check-ignore', '--no-index', rel], root).length > 0;
    if (pattern) {
      const owner = Object.keys(UNTRACKED).find((p) => matches(p, rel));
      if (!owner) {
        problems.push(`${rel}: .gitignore hides it, but no UNTRACKED entry says why`);
        continue;
      }
      claimed.add(owner);
      if (tracked.has(rel)) problems.push(`${rel}: ignored by pattern yet still in the index — run git rm --cached`);
      continue;
    }
    if (!tracked.has(rel)) problems.push(`${rel}: neither tracked nor ignored — it would reach no clone and no tag`);
  }

  for (const pattern of Object.keys(UNTRACKED)) {
    if (!claimed.has(pattern)) problems.push(`UNTRACKED names ${pattern}, which matches nothing — a stale reason is worse than none`);
  }
  return problems;
}

export function matches(pattern: string, path: string) {
  return globToRegExp(pattern).test(path);
}

function gitRun(args: string[], cwd: string) {
  const { stdout } = spawnSync(hostBinary('git', 'to read what the tree tracks, which is a question only git can answer'), args, { cwd, encoding: 'utf8' });
  return (stdout ?? '').split('\n').filter(Boolean);
}

export function unmarkedCoverageProblems(root = ROOT, run = gitRun) {
  const tracked = run(['ls-files'], root);
  return Object.keys(UNMARKED)
    .filter((pattern) => !tracked.some((path) => matches(pattern, path)))
    .map((pattern) => `UNMARKED names ${pattern}, which matches no tracked file — drop the exception`);
}

function main() {
  const problems = [...unmarkedProblems(), ...trackingProblems(), ...unmarkedCoverageProblems()];
  if (problems.length > 0) {
    for (const problem of problems) console.error(`check-generated: ${problem}`);
    console.error(`\ncheck-generated: ${problems.length} problem(s)`);
    process.exit(1);
  }
  console.log(
    `check-generated: every generated file names itself; ${Object.keys(UNTRACKED).length} ignore pattern(s) `
    + `and ${Object.keys(UNMARKED).length} unmarked output(s) carry a reason`,
  );
}

if (isMainModule(import.meta.url)) main();
