import test from 'node:test';
import assert from 'node:assert/strict';
import {
  collect, sentenceProblems, sentencesIn, blocks, plain, clauseCount, unnamedSubject, inScope,
  blanked, unregioned,
  excusedBy, scoped, zeroScanProblems, staleSpecProblems, staleExemptProblems,
  NOT_YET_REWRITTEN, MAX_WORDS, MAX_CLAUSES,
} from './check-register.ts';

const long = `A sentence written to run past the limit this gate holds, carrying one claim and `
  + 'then a second one about something else entirely, and a third about a fourth thing nobody '
  + 'asked after.';

test('this tree holds every consumer document it has not excused', () => {
  assert.deepEqual(collect(), []);
});

test('a sentence past the word limit is reported, and one inside it is not', () => {
  const problems = sentenceProblems('a.md', long);
  assert.ok(problems.some((one) => /words, over 30/.test(one)));
  assert.deepEqual(sentenceProblems('a.md', 'Tokens are the only styling layer.'), []);
});

test('a second subordinate clause is reported, because each one is a claim to hold open', () => {
  assert.equal(clauseCount('The card is a surface, which reads tokens.'), 1);
  assert.equal(clauseCount('The card reads tokens, so it follows the skin, which the plugin sets.'), 2);
  assert.deepEqual(sentenceProblems('a.md', 'The card is a surface, which reads tokens.'), []);
  assert.match(
    sentenceProblems('a.md', 'The card reads tokens, so it follows the skin, which the plugin sets.')[0] ?? '',
    /subordinate clauses/,
  );
});

test('a comma before and is a list as often as a claim, so it is not counted', () => {
  assert.equal(clauseCount('The layer, the architecture, and the install.'), 0,
    'a gate calling a list a subordination reports a message that is false of the sentence');
  assert.deepEqual(sentenceProblems('a.md', 'It takes a label, a value, and a tone.').filter(
    (one) => /subordinate/.test(one)), []);
});

test('a sentence opening on a pronoun that names nothing is reported', () => {
  assert.equal(unnamedSubject('It draws the cell box.'), 'it');
  assert.equal(unnamedSubject('They read tokens.'), 'they');
  assert.equal(unnamedSubject('That is the whole install.'), 'that is');
  assert.equal(unnamedSubject('The same document holds it.'), 'the same');
  assert.equal(unnamedSubject('ArenaTableCell draws the cell box.'), null);
  assert.equal(unnamedSubject('This page routes.'), null,
    'a demonstrative carrying a noun names its subject, and only a bare one does not');
  assert.equal(unnamedSubject('Those four documents are large.'), null);
  assert.equal(unnamedSubject('Those are large.'), 'those are');
});

test('a fenced block is what a reader copies, and a generated region is judged where it is emitted', () => {
  const source = ['Prose here.', '', '```tsx', long, '```', '',
    '<!-- @language GENERATED by a script. -->', long, '<!-- @language end -->'].join('\n');
  assert.deepEqual(sentenceProblems('a.md', source), []);
});

test('a code span is one word and a link is its text, so neither inflates a count', () => {
  assert.equal(plain('Read `var(--sp-4)` through its token.'), 'Read CODE through its token.');
  assert.equal(plain('See [`page.md`](./references/page.md).'), 'See CODE.');
  assert.equal(plain('**Bold** and *thin*.'), 'Bold and thin.');
});

test('a paragraph is one block and a table row is one block per cell', () => {
  const found = blocks('One line\nand its wrap.\n\n| a | b |\n');
  assert.equal(found.length, 3);
  assert.equal(found[0]?.text, 'One line and its wrap.');
  assert.deepEqual([found[1]?.text, found[2]?.text], ['a', 'b']);
});

test('a sentence carries the line its block opens on, so a report points somewhere', () => {
  const found = sentencesIn('First.\n\nSecond one here.\n');
  assert.deepEqual(found.map((one) => one.line), [1, 3]);
});

test('the branch this gate reads is the consumer one, and the router with it', () => {
  assert.equal(inScope('skills/design/SKILL.md'), true,
    'the router is carved out of the consumer-document test in check-docs.ts for a different '
    + 'reason, and it is the page whose register the rest are measured against');
  assert.equal(inScope('skills/design/references/page.md'), true);
  assert.equal(inScope('frameworks/react/components/forms/arena-radio/ArenaRadio.prompt.md'), true);
  assert.equal(inScope('AGENTS.md'), false);
  assert.equal(inScope('scripts/check/arena/AGENTS.md'), false);
  assert.ok(scoped().length > 100, 'the branch is more than a handful of pages');
});

test('an allowance names a pathspec, and a document under one is excused by it', () => {
  assert.equal(excusedBy('AGENTS.md'), null, 'the other branch is not this gate\'s subject');
  const spec = [...NOT_YET_REWRITTEN.keys()][0] ?? '';
  assert.ok(scoped().some((rel) => excusedBy(rel) === spec),
    'every entry left in the map still matches a document this gate reads');
  const excused = scoped().filter((rel) => excusedBy(rel) !== null);
  const held = scoped().filter((rel) => excusedBy(rel) === null);
  assert.equal(excused.length + held.length, scoped().length,
    'every document this gate reads is either excused by one entry or held by the register');
  assert.ok(held.length > 0,
    'a rewritten document leaves the map, so this list grows and the entries shrink. Naming one '
    + 'here would make every rewrite a suite edit, which is the chore this derivation avoids');
});

test('an allowance whose every document already reads in this register fails as stale', () => {
  const one = [...NOT_YET_REWRITTEN.keys()][0] ?? '';
  assert.equal(staleSpecProblems(new Map([[one, false]])).length, NOT_YET_REWRITTEN.size - 1,
    'every entry the run did not reach is reported as matching nothing');
  assert.match(staleSpecProblems(new Map([[one, true]]))[0] ?? '',
    /An allowance is not an exemption/);
});

test('an empty scan and a stale exemption are failures rather than a quiet pass', () => {
  assert.deepEqual(zeroScanProblems(['a.md']), []);
  assert.match(zeroScanProblems([])[0] ?? '', /passed over nothing/);
  assert.deepEqual(staleExemptProblems(['a.md']), []);
});

test('the two limits are the ones the reports name, so a message cannot drift from the rule', () => {
  assert.equal(MAX_WORDS, 30);
  assert.equal(MAX_CLAUSES, 1);
  assert.match(sentenceProblems('a.md', long).join('\n'), new RegExp(`over ${MAX_WORDS}`));
});


test('the frontmatter is metadata rather than prose, and blanking it keeps the line numbers true', () => {
  const source = ['---', 'name: design', 'description: "a long quoted sentence"', '---', '', long].join('\n');
  assert.equal(blanked(source).split('\n').length, source.split('\n').length);
  const found = sentenceProblems('a.md', source);
  assert.ok(found.every((one) => !/name: design/.test(one)),
    'a description held at 1024 characters by check:skill-spec and quoted verbatim into llms.txt '
    + 'is not a sentence this gate may ask anybody to split');
  assert.ok(found.every((one) => /:6:/.test(one)), 'the report points at the line the prose is on');
});


test('a generated region and a fence are blanked in place, so a line number after one is true', () => {
  const source = ['Prose.', '', '<!-- @language GENERATED by a script. -->', 'Emitted.',
    '<!-- @language end -->', '', '```tsx', 'code()', '```', '', long].join('\n');
  assert.equal(unregioned(source).split('\n').length, source.split('\n').length);
  const found = sentenceProblems('a.md', source);
  assert.ok(found.length > 0, 'the sentence past the fence is still read');
  assert.ok(found.every((one) => /:11:/.test(one)),
    'a region that dropped its lines instead of blanking them reported every later line short');
});
